camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor_2_x.java
camel-k-runtime-bom/pom.xml
pom.xml

Create runtime bom

---

camel-knative/pom.xml

Runtime components should include catalog information

---

camel-k-runtime-groovy/pom.xml

Exclude groovy-all as well here

Need to exclude groovy-all here as well, possible for it to bleed in

---

camel-knative/src/main/java/org/apache/camel/component/knative/KnativeConfiguration.java
camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java
camel-knative/src/main/java/org/apache/camel/component/knative/ce/V01.java
camel-knative/src/main/java/org/apache/camel/component/knative/ce/V02.java
camel-knative/src/test/java/org/apache/camel/component/knative/CloudEventsV01Test.java
camel-knative/src/test/java/org/apache/camel/component/knative/CloudEventsV02Test.java

Fix #48: add a default type to cloudevents

---

camel-k-adapter-camel-3/pom.xml

This need to be fixed for the camel-k-merge Jenkins job
https://builds.apache.org/view/C/view/Apache%20Camel/job/camel-k-merge/79/console

Align the snapshot version for camel-k-adapter-camel-3 module

---

.travis.yml
pom.xml

update to Camel 2.24.0

---

camel-k-runtime-core/src/main/java/org/apache/camel/k/Constants.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/ContextCustomizer.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/RuntimeSupport.java
camel-k-runtime-core/src/test/java/org/apache/camel/k/support/NameCustomizer.java
camel-k-runtime-core/src/test/java/org/apache/camel/k/support/RuntimeSupportTest.java
camel-k-runtime-jvm/src/test/java/org/apache/camel/k/jvm/PropertiesTest.java

Refactor customizer activation

---

camel-k-runtime-groovy/src/main/groovy/org/apache/camel/k/groovy/dsl/ComponentsConfiguration.groovy
camel-k-runtime-groovy/src/main/groovy/org/apache/camel/k/groovy/dsl/IntegrationConfiguration.groovy
camel-k-runtime-groovy/src/main/groovy/org/apache/camel/k/groovy/dsl/RestConfiguration.groovy
camel-k-runtime-groovy/src/main/resources/integration.gdsl
camel-k-runtime-groovy/src/test/groovy/org/apache/camel/k/groovy/dsl/IntegrationTest.groovy
camel-k-runtime-groovy/src/test/resources/routes-with-error-handler.groovy

- add missing methods from route builder / builder support
- initial support for idea auto completion

improve groovy support

---

camel-k-runtime-yaml/src/main/java/org/apache/camel/k/yaml/YamlRoutesLoader.java
camel-k-runtime-yaml/src/main/java/org/apache/camel/k/yaml/model/Definitions.java
camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpComponent.java
camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEnvironment.java

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Remove unused SuppresWarnings

---

camel-k-runtime-jvm/pom.xml
camel-k-runtime-jvm/src/main/java/org/apache/camel/k/jvm/loader/JavaScriptLoader.java
pom.xml

Switch to GraalJS

---

camel-k-loader-groovy/pom.xml
camel-k-loader-js/pom.xml
camel-k-loader-js/src/main/java/org/apache/camel/k/loader/js/dsl/IntegrationConfiguration.java
camel-k-loader-js/src/test/java/org/apache/camel/k/loader/js/dsl/IntegrationTest.java
camel-k-loader-js/src/test/resources/routes-with-component-configuration.js

Fix JS symbol export

---

camel-k-loader-groovy/pom.xml
camel-k-loader-groovy/src/main/groovy/org/apache/camel/k/loader/groovy/GroovyRoutesLoader.groovy
camel-k-loader-groovy/src/main/groovy/org/apache/camel/k/loader/groovy/dsl/IntegrationConfiguration.groovy
camel-k-loader-groovy/src/test/groovy/org/apache/camel/k/loader/groovy/LoaderTest.groovy
camel-k-loader-groovy/src/test/resources/routes-with-endpoint-dsl.groovy
camel-k-loader-java/pom.xml
camel-k-loader-java/src/test/java/org/apache/camel/k/loader/java/RoutesLoaderTest.java
camel-k-loader-java/src/test/resources/MyRoutesWithEndpointDsl.java
camel-k-loader-js/pom.xml
camel-k-loader-js/src/main/java/org/apache/camel/k/loader/js/JavaScriptRoutesLoader.java
camel-k-loader-js/src/main/java/org/apache/camel/k/loader/js/dsl/IntegrationConfiguration.java
camel-k-loader-js/src/test/java/org/apache/camel/k/loader/js/RoutesLoaderTest.java
camel-k-loader-js/src/test/resources/routes-with-endpoint-dsl.js
camel-k-loader-kotlin/pom.xml
camel-k-loader-kotlin/src/main/kotlin/org/apache/camel/k/loader/kotlin/KotlinRoutesLoader.kt
camel-k-loader-kotlin/src/main/kotlin/org/apache/camel/k/loader/kotlin/dsl/IntegrationConfiguration.kt
camel-k-loader-kotlin/src/test/kotlin/org/apache/camel/k/loader/kotlin/LoaderTest.kt
camel-k-loader-kotlin/src/test/resources/routes-with-endpoint-dsl.kts
camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java

Allow endpoint DSL in Camel k

---

camel-k-runtime-core/pom.xml
pom.xml

add maven dependencies for the java.xml.bind (jaxb) module #103

maven dependencies for java.xml.bind (jaxb) issue #103

---

camel-knative-http/pom.xml
camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumerDispatcher.java
camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpProducer.java
camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
camel-knative/src/test/java/org/apache/camel/component/knative/KnativeComponentTest.java
examples/camel-k-runtime-example-knative/pom.xml
examples/camel-k-runtime-example-knative/src/main/resources/application.properties
examples/camel-k-runtime-example-knative/src/main/resources/env.json
examples/camel-k-runtime-example-knative/src/main/resources/routes.yaml
examples/pom.xml
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java
tooling/camel-k-maven-plugin/src/test/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3Test.java

knative-http component does not return response

---

camel-k-loader-groovy/src/main/groovy/org/apache/camel/k/loader/groovy/dsl/ComponentConfiguration.groovy
camel-k-loader-js/src/main/java/org/apache/camel/k/loader/js/dsl/IntegrationConfiguration.java
camel-k-loader-js/src/main/java/org/apache/camel/k/loader/js/dsl/ProcessorSupport.java
camel-k-loader-js/src/test/java/org/apache/camel/k/loader/js/dsl/IntegrationTest.java
camel-k-loader-js/src/test/resources/routes-with-processors.js
camel-k-loader-knative/src/main/java/org/apache/camel/k/loader/knative/KnativeSourceRoutesLoader.java
camel-k-loader-yaml/README.adoc
camel-k-loader-yaml/src/main/java/org/apache/camel/k/loader/yaml/parser/StepParser.java
camel-k-loader-yaml/src/main/java/org/apache/camel/k/loader/yaml/parser/StepParserSupport.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/PropertiesSupport.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/RuntimeSupport.java
camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpComponent.java
camel-knative/pom.xml
camel-knative/src/main/java/org/apache/camel/component/knative/KnativeComponent.java
camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java
camel-knative/src/test/java/org/apache/camel/component/knative/CloudEventsV01Test.java
camel-knative/src/test/java/org/apache/camel/component/knative/CloudEventsV02Test.java
camel-knative/src/test/java/org/apache/camel/component/knative/KnativeComponentTest.java
pom.xml
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java
tooling/camel-k-maven-plugin/src/test/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3Test.java

Update to Camel RC1

---

camel-k-runtime-servlet/src/main/java/org/apache/camel/k/servlet/ServletRegistration.java
examples/camel-k-runtime-example-quarkus-js/pom.xml
examples/camel-k-runtime-example-quarkus-knative/pom.xml
examples/camel-k-runtime-example-quarkus-yaml/pom.xml
examples/pom.xml

Disbale deploy task for examples

---

camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumer.java
camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTestSupport.java

Can't bridge two Knative channels with new component

---

camel-knative/camel-knative-api/src/main/java/org/apache/camel/component/knative/spi/CloudEvent.java
camel-knative/camel-knative-api/src/main/java/org/apache/camel/component/knative/spi/CloudEvents.java
camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java
camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/ce/AbstractCloudEventProcessor.java
camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/ce/CloudEventProcessors.java

Wrong CloudEvent Headers used

---

camel-knative/camel-knative-api/src/main/java/org/apache/camel/component/knative/spi/Knative.java
camel-knative/camel-knative-api/src/main/java/org/apache/camel/component/knative/spi/KnativeEnvironment.java
camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeComponent.java
camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeConfiguration.java
camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java
camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/ce/AbstractCloudEventProcessor.java

Provide support for statically defined cloudevent headers

---

camel-knative/camel-knative-api/src/main/java/org/apache/camel/component/knative/spi/CloudEvents.java
camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/ce/AbstractCloudEventProcessor.java

CamelCloudEventXXX not converted to CE header

---

tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/model/CamelArtifact.java
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/model/CatalogComponentDefinition.java
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/model/CatalogDataFormatDefinition.java
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/model/CatalogLanguageDefinition.java
tooling/camel-k-maven-plugin/src/test/java/org/apache/camel/k/tooling/maven/processors/AbstractCatalogProcessorTest.java
tooling/camel-k-maven-plugin/src/test/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3Test.java

Relates to https://github.com/apache/camel-k/issues/1095.

Add type information to catalog

---

camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java

entry #203
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Provide basic description for KNative component to have a valid catalog

---

camel-k-loader-java/src/main/java/org/apache/camel/k/loader/java/JavaSourceLoader.java
camel-k-loader-java/src/test/java/org/apache/camel/k/loader/java/RoutesLoaderTest.java
camel-k-loader-java/src/test/resources/MyRoutesWithPackageAndComment.java
camel-k-loader-java/src/test/resources/MyRoutesWithPackageAndLineComment.java

thx @valdar
Fixes apache/camel-k#1132

Ignore package when working with Java classes

---

camel-k-quarkus/camel-k-quarkus-loader-groovy/deployment/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-groovy/deployment/src/main/java/org/apache/camel/k/loader/groovy/quarkus/deployment/Feature.java
camel-k-quarkus/camel-k-quarkus-loader-groovy/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-groovy/runtime/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-java/deployment/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-java/deployment/src/main/java/org/apache/camel/k/loader/java/quarkus/deployment/Feature.java
camel-k-quarkus/camel-k-quarkus-loader-java/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-java/runtime/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-kotlin/deployment/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-kotlin/deployment/src/main/java/org/apache/camel/k/loader/kotlin/quarkus/deployment/Feature.java
camel-k-quarkus/camel-k-quarkus-loader-kotlin/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-kotlin/runtime/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-xml/it/src/main/resources/application.properties
camel-k-quarkus/camel-k-quarkus-loader-yaml/it/src/main/resources/application.properties
camel-k-runtime-bom/pom.xml
examples/camel-k-runtime-example-quarkus-groovy/data/application.properties
examples/camel-k-runtime-example-quarkus-groovy/data/routes.groovy
examples/camel-k-runtime-example-quarkus-groovy/pom.xml
examples/camel-k-runtime-example-quarkus-groovy/src/main/resources/application.properties
examples/camel-k-runtime-example-quarkus-java/data/MyRoutes.java
examples/camel-k-runtime-example-quarkus-java/data/application.properties
examples/camel-k-runtime-example-quarkus-java/pom.xml
examples/camel-k-runtime-example-quarkus-java/src/main/resources/application.properties
examples/camel-k-runtime-example-quarkus-knative/pom.xml
examples/camel-k-runtime-example-quarkus-yaml/pom.xml
examples/pom.xml
pom.xml

[quarkus] create loaders for java, groovy and kotlin in JVM mode

---

distribution/pom.xml
distribution/src/main/assemblies/repository.xml

Adding a repository distribution to serve as a m2 cache.

Add a repository distribution

---

camel-k-runtime-core/pom.xml
camel-k-runtime-core/src/main/java/org/apache/camel/k/Constants.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/listener/PropertiesFunctionsConfigurer.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/KubernetesPropertiesFunction.java
camel-k-runtime-core/src/main/resources/META-INF/services/org.apache.camel.k.Runtime$Listener
camel-k-runtime-core/src/test/java/org/apache/camel/k/listener/PropertiesFunctionsConfigurerTest.java
camel-k-runtime-core/src/test/resources/configmaps/my-cm/my-property
camel-k-runtime-core/src/test/resources/secrets/my-secret/my-property

Fixes #239
Fixes https://github.com/apache/camel-k/issues/1261

Allow to load generic secrets and reference entries from integrations

---

camel-k-runtime-bom/pom.xml
camel-k-runtime-master/pom.xml
camel-k-runtime-master/src/main/java/org/apache/camel/k/master/MasterContextCustomizer.java
camel-k-runtime-master/src/main/resources/META-INF/services/org/apache/camel/k/customizer/master
camel-k-runtime-master/src/test/java/org/apache/camel/k/master/MasterCustomizerTest.java
camel-k-runtime-master/src/test/resources/log4j2-test.xml
pom.xml

Fix #241: add master helper component

---

camel-k-quarkus/camel-k-runtime-quarkus/deployment/pom.xml
camel-k-quarkus/camel-k-runtime-quarkus/runtime/pom.xml
camel-k-runtime-main/pom.xml

Add camel-bean to transitive dependencies by default

---

tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java

Improve catalog

---

camel-k-quarkus/camel-k-quarkus-knative/runtime/pom.xml
tooling/camel-k-maven-plugin/src/it/generate-catalog-main/verify.groovy
tooling/camel-k-maven-plugin/src/it/generate-catalog-quarkus/verify.groovy
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/model/CamelArtifact.java
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java
tooling/camel-k-maven-plugin/src/test/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3Test.java

Knative extension not listed among knative dependencies in quarkus catalog

---

tooling/camel-k-maven-plugin/pom.xml

Add a check to ensure Maven 3.6.3+ is used

---

.github/workflows/pr-build.yml
camel-k-loader-kotlin/pom.xml
camel-k-loader-kotlin/src/main/kotlin/org/apache/camel/k/loader/kotlin/KotlinSourceLoader.kt
camel-k-loader-kotlin/src/main/kotlin/org/apache/camel/k/loader/kotlin/dsl/BeansConfiguration.kt
camel-k-loader-kotlin/src/main/kotlin/org/apache/camel/k/loader/kotlin/dsl/IntegrationConfiguration.kt
camel-k-loader-kotlin/src/main/resources/META-INF/services/org/apache/camel/k/loader/kts
pom.xml
tooling/camel-k-maven-plugin/pom.xml

Default to Java 11

---

camel-k-runtime-http/src/main/java/org/apache/camel/k/http/engine/RuntimePlatformHttpConsumer.java

Fix #301: Auto-set content-length or chunked transfer encoding

---

camel-k-main/camel-k-runtime-main/src/test/java/org/apache/camel/k/main/PropertiesTest.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/Constants.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/KubernetesPropertiesFunction.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/PropertiesSupport.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/RuntimeSupport.java
camel-k-runtime-core/src/test/java/org/apache/camel/k/support/RuntimeSupportTest.java
camel-k-runtime-webhook/src/test/java/org/apache/camel/k/webhook/WebhookTest.java
examples/camel-k-runtime-example-api/data/application.properties
examples/camel-k-runtime-example-knative/data/application.properties
examples/camel-k-runtime-example-rest/data/application.properties
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java

Set camel.k.customizer as base property for customizer

---

camel-k-loader-js/src/main/java/org/apache/camel/k/loader/js/dsl/IntegrationConfiguration.java
camel-k-loader-js/src/test/java/org/apache/camel/k/loader/js/dsl/IntegrationTest.java
camel-k-loader-js/src/test/resources/routes-with-context-configuration.js

Fixes #340
Fixes apache/camel-k#1346

'context' object not available in JavaScript integrations

---

tooling/camel-k-maven-plugin/src/it/generate-catalog-main/verify.groovy
tooling/camel-k-maven-plugin/src/it/generate-catalog-quarkus/verify.groovy
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

Add circuit-breaker capability

---

camel-k-main/camel-k-runtime-tracing/pom.xml
camel-k-main/camel-k-runtime-tracing/src/main/java/org/apache/camel/k/tracing/TracingContextCustomizer.java
camel-k-main/camel-k-runtime-tracing/src/test/java/org/apache/camel/k/tracing/TracingContextCustomizerTest.java
camel-k-main/camel-k-runtime-tracing/src/test/resources/log4j2-test.xml
camel-k-runtime-bom/pom.xml
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/RuntimeSupport.java
pom.xml
tooling/camel-k-maven-plugin/src/it/generate-catalog-main/verify.groovy
tooling/camel-k-maven-plugin/src/it/generate-catalog-quarkus/verify.groovy
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

Add an opentracing capability

---

camel-k-runtime-core/src/main/java/org/apache/camel/k/support/KubernetesPropertiesFunction.java
camel-k-runtime-core/src/test/java/org/apache/camel/k/listener/PropertiesFunctionsConfigurerTest.java
camel-knative/camel-knative/src/generated/resources/org/apache/camel/component/knative/knative.json

Integration should fail when no secret is found

---

camel-k-runtime-knative/src/main/java/org/apache/camel/k/loader/knative/KnativeSourceLoaderInterceptor.java
camel-k-runtime-knative/src/test/java/org/apache/camel/k/loader/knative/KnativeSourceRoutesLoaderTest.java
camel-k-runtime-knative/src/test/resources/sources/routes.groovy
camel-k-runtime-knative/src/test/resources/sources/routes.java
camel-k-runtime-knative/src/test/resources/sources/routes.js
camel-k-runtime-knative/src/test/resources/sources/routes.kts
camel-k-runtime-knative/src/test/resources/sources/routes.xml
camel-knative/camel-knative-api/src/main/java/org/apache/camel/component/knative/spi/Knative.java
camel-knative/camel-knative-api/src/main/java/org/apache/camel/component/knative/spi/KnativeEnvironment.java
camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpProducer.java
camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java
camel-knative/camel-knative/src/test/java/org/apache/camel/component/knative/KnativeComponentTest.java

Fixes #365
Fixes #369
Fixes #371

Add runtime support for Knative sinkbinding

---

camel-knative/camel-knative/pom.xml

Use the new camel-component-maven-plugin from Camel 3.4

---

tooling/camel-k-catalog/pom.xml
tooling/pom.xml

publish the camel-k catalog as artifact

---

camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumer.java
camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpProducer.java
camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpSupport.java
camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpTransport.java
camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpServer.java
camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTestSupport.java
camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/assertions/HttpServerRequestAssert.java
camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeConfiguration.java

camel-knative: don't replace message when the producers completes

---

pom.xml

Bump Jandex to 2.2.1.Final

---

camel-k-loader-kotlin/camel-k-loader-kotlin/pom.xml
camel-k-loader-kotlin/camel-k-loader-kotlin/src/main/kotlin/org/apache/camel/k/loader/kotlin/KotlinCompilationConfiguration.kt
pom.xml

[kotlin] compile scripts wit the same target level used to compile the loader

---

pom.xml

chore(deps): update vert.x to v3.9.1

---

pom.xml

Upgrade Vertx to version 3.9.2

---

pom.xml

Upgrade Commons Lang to version 3.11

---

camel-k-loader-yaml/camel-k-loader-yaml/src/test/groovy/org/apache/camel/k/loader/yaml/DefinitionsTest.groovy
camel-k-loader-yaml/camel-k-loader-yaml/src/test/groovy/org/apache/camel/k/loader/yaml/RoutesTest.groovy
camel-k-loader-yaml/camel-k-loader-yaml/src/test/groovy/org/apache/camel/k/loader/yaml/TestSupport.groovy

chore(test): cleanup yaml unit tests

---

pom.xml

Update commons text to version 1.9

---

pom.xml

Upgrade Jackson to version 2.10.5

---

camel-k-loader-groovy/src/main/groovy/org/apache/camel/k/loader/groovy/GroovySourceLoader.groovy
camel-knative/camel-knative/src/generated/resources/org/apache/camel/component/knative/knative.json

Fix #394: unable to run Groovy routes on Quarkus

---

.asf.yaml

Disable merge commits on pull requests

---

camel-k-main/camel-k-runtime-main/src/test/java/org/apache/camel/k/main/PropertiesTest.java

Fixed properties test to use correct way of main configurations

---

pom.xml

Update maven plugin dependencies

---

pom.xml

Upgrade to camel-quarkus v1.0.0

---

camel-k-loader-kotlin/camel-k-loader-kotlin/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-kotlin/runtime/pom.xml
pom.xml

chore(deps): update kotlin to v1.4.0

---

pom.xml
tooling/pmd-ruleset.xml

chore(build): tune and enable pmd on sourcecheck profile

---

.github/workflows/ci-build.yml

build(ci): build on push and skip build for some paths

---

pom.xml
tooling/camel-k-test/pom.xml

build(deps): add junit-pioneer to ease test that require env vars or properties

---

camel-k-loader-groovy/src/main/groovy/org/apache/camel/k/loader/groovy/dsl/BeanConfiguration.groovy
camel-k-loader-groovy/src/main/groovy/org/apache/camel/k/loader/groovy/dsl/ComponentsConfiguration.groovy
camel-k-loader-groovy/src/main/groovy/org/apache/camel/k/loader/groovy/dsl/IntegrationConfiguration.groovy
camel-k-loader-groovy/src/main/groovy/org/apache/camel/k/loader/groovy/dsl/Support.groovy
camel-k-loader-groovy/src/main/groovy/org/apache/camel/k/loader/groovy/extension/CamelContextExtensions.groovy
camel-k-loader-groovy/src/main/groovy/org/apache/camel/k/loader/groovy/extension/ExpressionClauseExtensions.groovy
camel-k-loader-groovy/src/main/groovy/org/apache/camel/k/loader/groovy/extension/LogComponentExtension.groovy
camel-k-loader-groovy/src/main/groovy/org/apache/camel/k/loader/groovy/extension/ProcessorDefinitionExtensions.groovy
camel-k-loader-groovy/src/main/resources/META-INF/services/org.codehaus.groovy.runtime.ExtensionModule
camel-k-loader-groovy/src/test/groovy/org/apache/camel/k/loader/groovy/LoaderTest.groovy
camel-k-loader-groovy/src/test/groovy/org/apache/camel/k/loader/groovy/dsl/IntegrationTest.groovy
camel-k-loader-groovy/src/test/groovy/org/apache/camel/k/loader/groovy/dsl/extension/ExpressionClauseExtensionTest.groovy
camel-k-loader-groovy/src/test/groovy/org/apache/camel/k/loader/groovy/support/TestRuntime.groovy
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/RouteBuilders.java

groovy: cleanup loader and tests

---

docs/modules/languages/pages/groovy.adoc
docs/modules/languages/pages/javascript.adoc
docs/modules/languages/pages/kotlin.adoc
docs/modules/languages/pages/yaml.adoc
examples/camel-k-runtime-example-rest/README.adoc

chore: Minor docs & code sample fixes

---

pom.xml

Upgrade Assertj to version 3.17.1

---

camel-k-loader-groovy/pom.xml
camel-k-loader-groovy/src/test/groovy/org/apache/camel/k/loader/groovy/GroovySourceLoaderTest.groovy
camel-k-loader-groovy/src/test/groovy/org/apache/camel/k/loader/groovy/support/MyBean.groovy
camel-k-loader-kotlin/camel-k-loader-kotlin/pom.xml
camel-k-loader-kotlin/camel-k-loader-kotlin/src/test/kotlin/org/apache/camel/k/loader/kotlin/KotlinSourceLoaderTest.kt
camel-k-loader-kotlin/camel-k-loader-kotlin/src/test/kotlin/org/apache/camel/k/loader/kotlin/support/MyBean.kt
camel-k-loader-kotlin/camel-k-loader-kotlin/src/test/resources/routes-with-beans.kts
camel-k-loader-yaml/camel-k-loader-yaml-common/pom.xml
camel-knative/camel-knative-api/pom.xml
camel-knative/camel-knative/pom.xml
pom.xml
tooling/camel-k-maven-plugin/pom.xml
tooling/camel-k-maven-plugin/src/it/generate-dependencies/verify.groovy
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateDependencyListMojo.java
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateYamlParserSupportClasses.java
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/support/MavenSupport.java

Cleanup dependencies

---

.github/workflows/automatic-changelog-update.yml

Added an automatic changelog gh action

---

.github/workflows/automatic-changelog-update.yml

Changelog updater: run every hour

---

.github/workflows/automatic-changelog-update.yml

Automatic changelog: Let's run during the night just one time

---

README.adoc

```release-note
Switch official chat from Gitter to Zulip (https://camel.zulipchat.com)
```

Switch from Gitter to Zulip

---

.github/workflows/ci-build.yml
camel-k-quarkus/camel-k-quarkus-core/deployment/src/main/java/org/apache/camel/k/core/quarkus/deployment/DeploymentProcessor.java
camel-k-quarkus/camel-k-quarkus-core/deployment/src/main/java/org/apache/camel/k/core/quarkus/deployment/DeploymentSupport.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-master/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-master/src/main/java/org/apache/camel/k/quarkus/master/Application.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-master/src/main/resources/application.properties
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-master/src/test/java/org/apache/camel/k/quarkus/master/MasterIT.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-master/src/test/java/org/apache/camel/k/quarkus/master/MasterTest.java
camel-k-quarkus/camel-k-quarkus-master/deployment/pom.xml
camel-k-quarkus/camel-k-quarkus-master/deployment/src/main/java/org/apache/camel/k/quarkus/master/deployment/Feature.java
camel-k-quarkus/camel-k-quarkus-master/pom.xml
camel-k-quarkus/camel-k-quarkus-master/runtime/pom.xml
camel-k-quarkus/pom.xml
camel-k-runtime-bom/pom.xml
pom.xml
tooling/camel-k-maven-plugin/src/it/generate-catalog-main/verify.groovy
tooling/camel-k-maven-plugin/src/it/generate-catalog-quarkus/verify.groovy
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

Fixes #470
```release-note
It is now possible to use the master component when running on Quarkus
```

Create an extension fot camel-k-runtime-master

---

.github/workflows/ci-build.yml

chore(build): enable native tests for js loader

---

camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-cron/src/main/java/org/apache/camel/k/quarkus/cron/deployment/Application.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime/src/main/java/org/apache/camel/k/quarkus/it/Application.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime/src/test/java/org/apache/camel/k/quarkus/it/RuntimeTest.java
camel-k-quarkus/camel-k-runtime-quarkus/runtime/src/main/java/org/apache/camel/k/quarkus/Application.java
camel-k-quarkus/camel-k-runtime-quarkus/runtime/src/main/java/org/apache/camel/k/quarkus/ApplicationProducers.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/DelegatingRuntime.java
tooling/camel-k-maven-plugin/src/it/generate-catalog-quarkus/verify.groovy
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

Quarkus runtime improvements

---

camel-k-runtime-core/src/main/java/org/apache/camel/k/support/RuntimeSupport.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/SourcesSupport.java
camel-k-runtime-cron/src/main/java/org/apache/camel/k/cron/CronSourceLoaderInterceptor.java
camel-k-runtime-knative/src/main/java/org/apache/camel/k/loader/knative/KnativeSourceLoaderInterceptor.java

loaders: simplify source loader interceptors

---

camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime/src/main/java/org/apache/camel/k/quarkus/it/Application.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime/src/test/java/org/apache/camel/k/quarkus/it/RuntimeTest.java
camel-k-quarkus/camel-k-runtime-quarkus/deployment/src/main/java/org/apache/camel/k/quarkus/deployment/DeploymentProcessor.java
camel-k-quarkus/camel-k-runtime-quarkus/runtime/src/main/java/org/apache/camel/k/quarkus/Application.java
camel-k-quarkus/camel-k-runtime-quarkus/runtime/src/main/java/org/apache/camel/k/quarkus/ApplicationRecorder.java

quarkus: disable routes discovery as routes are programmatically added

---

camel-k-loader-groovy/pom.xml
camel-k-loader-java/pom.xml
camel-k-loader-js/pom.xml
camel-k-loader-kotlin/camel-k-loader-kotlin/pom.xml
camel-k-loader-xml/pom.xml
camel-k-loader-yaml/camel-k-loader-yaml-common/pom.xml
camel-k-loader-yaml/camel-k-loader-yaml-support/pom.xml
camel-k-loader-yaml/camel-k-loader-yaml/pom.xml
camel-k-main/camel-k-runtime-health/pom.xml
camel-k-main/camel-k-runtime-tracing/pom.xml
camel-k-runtime-core/pom.xml
camel-k-runtime-cron/pom.xml
camel-k-runtime-http/pom.xml
camel-k-runtime-knative/pom.xml
camel-k-runtime-webhook/pom.xml
camel-kamelet/pom.xml
camel-knative/camel-knative-api/pom.xml
camel-knative/camel-knative-http/pom.xml
camel-knative/camel-knative/pom.xml
pom.xml
tooling/camel-k-catalog/pom.xml
tooling/camel-k-maven-plugin/pom.xml

chore(build): use dependency management for dependencies and plugins

---

tooling/camel-k-maven-plugin/src/it/generate-catalog-main/verify.groovy
tooling/camel-k-maven-plugin/src/it/generate-catalog-quarkus/verify.groovy
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java

Fixes #492
```release-note
NONE
```

Fix kamelet entry in catalog

---

.github/workflows/ci-build.yml
camel-k-quarkus/camel-k-quarkus-core/deployment/src/main/java/org/apache/camel/k/core/quarkus/deployment/DeploymentProcessor.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-java/src/main/java/org/apache/camel/k/loader/java/quarkus/Application.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-java/src/test/java/org/apache/camel/k/loader/java/java/JavaLoaderTest.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime-kamelet/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime-kamelet/src/main/java/org/apache/camel/k/quarkus/it/Application.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime-kamelet/src/main/resources/application.properties
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime-kamelet/src/test/java/org/apache/camel/k/quarkus/it/RuntimeIT.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime-kamelet/src/test/java/org/apache/camel/k/quarkus/it/RuntimeTest.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime-kamelet/src/test/resources/routes.properties
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime-kamelet/src/test/resources/routes/route.yaml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime-kamelet/src/test/resources/routes/set-body.yaml
camel-k-quarkus/camel-k-quarkus-itests/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-java/deployment/src/main/java/org/apache/camel/k/loader/java/quarkus/deployment/JavaSourceLoaderProcessor.java
camel-k-quarkus/camel-k-quarkus-loader-java/runtime/src/main/java/org/apache/camel/k/loader/java/quarkus/JavaSourceLoaderRecorder.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/SourcesSupport.java

Fixes #493
```release-note
NONE
```

Failed to start Kamelet

---

camel-kamelet/src/main/java/org/apache/camel/component/kamelet/KameletEndpoint.java
camel-kamelet/src/test/java/org/apache/camel/component/kamelet/KameletRouteTest.java

Reproducer for #500
```release-note
NONE
```

Sink Kamelet not called

---

camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-core/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-cron/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-kamelet/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-knative/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-groovy/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-java/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-js/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-kotlin/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-xml/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-yaml/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-master/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-polyglot/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-runtime/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-wrap/pom.xml

chore(build): add virtual deps to quarkus itests to ensure test have correct dependency tree on deployment artifacts

---

camel-k-main/camel-k-runtime-main/src/test/java/org/apache/camel/k/main/RuntimeTest.java
camel-k-quarkus/camel-k-quarkus-knative/deployment/src/main/java/org/apache/camel/k/quarkus/knative/deployment/DeploymentProcessor.java
camel-k-runtime-knative/src/main/java/org/apache/camel/k/knative/customizer/KnativeSinkBindingContextCustomizer.java
camel-k-runtime-knative/src/test/java/org/apache/camel/k/knative/customizer/KnativeSinkBindingCustomizerTest.java
camel-k-runtime-knative/src/test/java/org/apache/camel/k/loader/knative/KnativeSourceRoutesLoaderTest.java
components/camel-knative/camel-knative-api/pom.xml
components/camel-knative/camel-knative-api/src/main/java/org/apache/camel/component/knative/spi/KnativeEnvironment.java
components/camel-knative/camel-knative-api/src/main/java/org/apache/camel/component/knative/spi/KnativeTransport.java
components/camel-knative/camel-knative-api/src/test/java/org/apache/camel/component/knative/spi/KnativeEnvironmentTest.java
components/camel-knative/camel-knative-http/pom.xml
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumer.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpProducer.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpSupport.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpTransport.java
components/camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
components/camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTestSupport.java
components/camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/assertions/HttpServerRequestAssert.java
components/camel-knative/camel-knative-test/src/main/java/org/apache/camel/component/knative/test/KnativeEnvironmentSupport.java
components/camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java
components/camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/ce/AbstractCloudEventProcessor.java
components/camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/ce/CloudEventProcessor.java
components/camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/ce/CloudEventProcessors.java
components/camel-knative/camel-knative/src/test/java/org/apache/camel/component/knative/KnativeComponentTest.java
components/camel-knative/camel-knative/src/test/java/org/apache/camel/component/knative/KnativeTransportNoop.java
components/camel-knative/camel-knative/src/test/resources/environment_classic.json

Fixes #453
```release-note
NONE
```

knative: refactor knative environment definition

---

docs/modules/languages/pages/yaml.adoc

Fixes #484
```release-note
NONE
```

yaml dsl: add documentation for endpoint-dsl support

---

.github/workflows/automatic-changelog-update.yml

Fixes changelog to run only on master

---

components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumer.java

knative(http): use async processor to process http requests

---

camel-k-main/camel-k-runtime-main/src/main/java/org/apache/camel/k/main/ApplicationRuntime.java
camel-k-quarkus/camel-k-runtime-quarkus/deployment/src/main/java/org/apache/camel/k/quarkus/deployment/DeploymentProcessor.java
camel-k-quarkus/camel-k-runtime-quarkus/runtime/src/main/java/org/apache/camel/k/quarkus/Application.java
camel-k-quarkus/camel-k-runtime-quarkus/runtime/src/main/java/org/apache/camel/k/quarkus/ApplicationRecorder.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/Runtime.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/RuntimeSupport.java
examples/camel-k-runtime-example-quarkus-yaml/data/routes.yaml

Fixes #512
```release-note
NONE
```

Log runtime version when starting

---

components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumer.java

knative(http): fix request handler exception handling

---

components/camel-knative/camel-knative-api/src/main/java/org/apache/camel/component/knative/spi/KnativeEnvironment.java
components/camel-knative/camel-knative-api/src/test/java/org/apache/camel/component/knative/spi/KnativeEnvironmentTest.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumer.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpProducer.java
components/camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
components/camel-knative/camel-knative/src/test/java/org/apache/camel/component/knative/KnativeComponentTest.java

knative: cleanup knative environment definition leftovers

---

camel-k-main/camel-k-runtime-main/src/main/java/org/apache/camel/k/main/ApplicationSupport.java
camel-k-main/camel-k-runtime-main/src/test/java/org/apache/camel/k/main/ApplicationSupportTest.java
camel-k-main/camel-k-runtime-main/src/test/resources/logger.properties

Logger configuration needs to be updated so changes come into effect
```release-note
NONE
```

fix: Update loggers after configuration

---

.github/workflows/automatic-changelog-update.yml

Add workflow dispatch to changelog gh action

---

Jenkinsfile

Jenkinsfile build: changed the JDK name following INFRA new approach

---

camel-k-loader-groovy/src/test/groovy/org/apache/camel/k/loader/groovy/GroovySourceLoaderIssuesTest.groovy
camel-k-loader-groovy/src/test/resources/issues/github-529.groovy

Fixes #529
```release-note
NONE
```

Groovy - such property: DELEGATE_FIRST when mapping beans

---

camel-k-loader-yaml/camel-k-loader-yaml-common/src/main/java/org/apache/camel/k/loader/yaml/parser/FromStepParser.java
camel-k-loader-yaml/camel-k-loader-yaml-common/src/main/java/org/apache/camel/k/loader/yaml/parser/RouteStepParser.java
camel-k-loader-yaml/camel-k-loader-yaml-common/src/main/java/org/apache/camel/k/loader/yaml/parser/ToDynamicStepParser.java
camel-k-loader-yaml/camel-k-loader-yaml-common/src/main/java/org/apache/camel/k/loader/yaml/parser/ToStepParser.java
camel-k-loader-yaml/camel-k-loader-yaml-common/src/main/java/org/apache/camel/k/loader/yaml/parser/WireTapStepParser.java
camel-k-loader-yaml/camel-k-loader-yaml-common/src/main/java/org/apache/camel/k/loader/yaml/support/StepParserSupport.java
camel-k-loader-yaml/camel-k-loader-yaml/pom.xml
camel-k-loader-yaml/camel-k-loader-yaml/src/generated/resources/camel-yaml-dsl.json
camel-k-loader-yaml/camel-k-loader-yaml/src/test/groovy/org/apache/camel/k/loader/yaml/RoutesWithPlaceholdersTest.groovy
camel-k-loader-yaml/camel-k-loader-yaml/src/test/groovy/org/apache/camel/k/loader/yaml/RoutesWithSecretsTest.groovy
camel-k-loader-yaml/camel-k-loader-yaml/src/test/groovy/org/apache/camel/k/loader/yaml/parser/FromTest.groovy
camel-k-loader-yaml/camel-k-loader-yaml/src/test/groovy/org/apache/camel/k/loader/yaml/parser/ToTest.groovy
camel-k-loader-yaml/camel-k-loader-yaml/src/test/resources/routes/RoutesWithSecretsTest_route.yaml
camel-k-loader-yaml/camel-k-loader-yaml/src/test/resources/routes/RoutesWithSecretsTest_route_property.yaml
camel-k-loader-yaml/camel-k-loader-yaml/src/test/resources/routes/RoutesWithSecretsTest_route_raw.yaml

yaml: auto wrap secret values wit RAW

---

.github/workflows/ci-build.yml
.github/workflows/pr-validate.yml
components/camel-kamelet/src/main/java/org/apache/camel/component/kamelet/KameletComponent.java

kamelet: use raw url

---

.github/workflows/ci-build-cleanup.yaml

build(actions): cancel stale workflow runs

---

components/camel-kamelet/src/main/java/org/apache/camel/component/kamelet/KameletComponent.java
components/camel-kamelet/src/test/java/org/apache/camel/component/kamelet/KameletPropertiesTest.java

kamelet: ensure URL encoded values is properly handled

---

examples/cron/data/application.properties
examples/cron/src/main/resources/application.properties
examples/groovy/data/application.properties
examples/groovy/src/main/resources/application.properties
examples/java/data/application.properties
examples/java/src/main/resources/application.properties
examples/js/data/application.properties
examples/js/src/main/resources/application.properties
examples/kamelets/data/application.properties
examples/kamelets/src/main/resources/application.properties
examples/knative/data/application.properties
examples/knative/src/main/resources/application.properties
examples/kotlin/data/application.properties
examples/kotlin/src/main/resources/application.properties
examples/xml/data/application.properties
examples/xml/src/main/resources/application.properties
examples/yaml/data/application.properties
examples/yaml/src/main/resources/application.properties

Cleanup examples

---

camel-k-core/support/src/main/java/org/apache/camel/k/support/RuntimeSupport.java

Fixes #548
```release-note
NONE
```

Error with leader election examples

---

.github/workflows/ci-build.yml

chore(ci): temporarily disable flacky jobs

---

camel-k-knative/consumer/runtime/pom.xml
camel-k-knative/runtime/pom.xml
itests/camel-k-itests-knative-sinkbinding/pom.xml

knative: fix wrong dependencies

---

camel-k-master/impl/src/main/java/org/apache/camel/k/master/MasterContextCustomizer.java
itests/camel-k-itests-master/src/main/java/org/apache/camel/k/quarkus/master/Application.java
itests/camel-k-itests-master/src/main/resources/application.properties
itests/camel-k-itests-master/src/test/java/org/apache/camel/k/quarkus/master/MasterTest.java

chore: enable new rebalacing features in customizer

---

pom.xml

chore: align kotlin libs to Quarkus release

---

.github/workflows/ci-build-cleanup.yaml

chore(actions): switch to potiuk/cancel-workflow-runs

---

.github/dependabot.yml
.github/workflows/ci-build.yml
pom.xml

update camel-quarkus to v1.6.0

---

support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java

```release-note
Fixes #589, fixed kamelet-reify component scheme in CamelK catalog
```

Fixes #589, fixed kamelet-reify component scheme in CamelK catalog

---

camel-k-cron/deployment/pom.xml
camel-k-cron/runtime/pom.xml
support/camel-k-maven-plugin/pom.xml
support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java

Fixes #592
```release-note
NONE
```

Catalog contains duplicate entry for same schema

---

.github/workflows/backport.yml
.gitmodules

Backport action 

---

.github/workflows/backport.yml

Fixed backport action

---

README.adoc

Reverts apache/camel-k-runtime#598

Revert "Test PR"

---

.github/workflows/backport.yml

Backport action

---

.github/workflows/automatic-changelog-update.yml
.gitmodules

Changelog action

---

examples/java/README.md

Add README to examples, java example

---

examples/cron/README.md

Added README for cron example

---

examples/kafka-source-s3/README.md
examples/kafka-source-s3/data/MyRoutes.java
examples/kafka-source-s3/data/application.properties
examples/kafka-source-s3/pom.xml
examples/kafka-source-s3/src/main/resources/application.properties
examples/pom.xml

Kafka source to AWS S3 Java Example

---

examples/java/README.md

Java Example: Fixed README Markdown

---

examples/cron/README.md

Cron Example: Fixed README Markdown

---

examples/kafka-source-s3/README.md

Kafka Source S3: Fixed README Markdown

---

README.adoc

doc: run local camel k runtime

---

pom.xml

Maven-Enforcer-plugin: Set the minimal maven version to 3.6.3

---

pom.xml

Bump to Kotlin 1.4.30

---

examples/cron/README.md
examples/cron/pom.xml
examples/groovy/pom.xml
examples/java/README.md
examples/java/pom.xml
examples/js/pom.xml
examples/kafka-source-s3/README.md
examples/kafka-source-s3/pom.xml
examples/kamelets/pom.xml
examples/knative/pom.xml
examples/kotlin/pom.xml
examples/xml/pom.xml
examples/yaml/pom.xml

The issue with the examples was caused by change in the structure of built quarkus projects after the upgrade for more info about the issue see: https://github.com/apache/camel-k-runtime/issues/641
```release-note
fix(examples) - update path to runner.jar
```

fix(examples) - update path to runner.jar

---

camel-k-core/support/src/main/java/org/apache/camel/k/support/SourcesSupport.java

Fixes #651
```release-note
NONE
```

Cron loader fails to start

---

camel-k-loader-jsh/impl/pom.xml
pom.xml

chore(deps): remove unused version properties

---

camel-k-loader-yaml/impl/src/main/java/org/apache/camel/k/loader/yaml/YamlDeserializerEndpointAwareBase.java
camel-k-loader-yaml/impl/src/main/java/org/apache/camel/k/loader/yaml/YamlSourceLoaderDeserializerResolver.java
camel-k-loader-yaml/impl/src/main/java/org/apache/camel/k/loader/yaml/deserializers/SagaActionUriDefinitionDeserializer.java
camel-k-loader-yaml/impl/src/main/java/org/apache/camel/k/loader/yaml/deserializers/ToDefinitionDeserializer.java
camel-k-loader-yaml/impl/src/main/java/org/apache/camel/k/loader/yaml/deserializers/ToDynamicDefinitionDeserializer.java
camel-k-loader-yaml/impl/src/test/groovy/org/apache/camel/k/loader/yaml/YamlSourceLoaderTest.groovy
camel-k-loader-yaml/impl/src/test/resources/yaml/routes_to_dynamic.yaml
camel-k-loader-yaml/impl/src/test/resources/yaml/routes_to_dynamic_alias.yaml
camel-k-loader-yaml/impl/src/test/resources/yaml/routes_to_dynamic_alias_out_of_order.yaml
camel-k-loader-yaml/impl/src/test/resources/yaml/routes_to_dynamic_out_of_order.yaml
camel-k-loader-yaml/impl/src/test/resources/yaml/routes_to_out_of_order.yaml

Fixes https://github.com/apache/camel-k/issues/2203
See: 
- https://issues.apache.org/jira/browse/CAMEL-16490
- https://issues.apache.org/jira/browse/CAMEL-16489
```release-note
NONE
```

Yaml DSL: add workarounds for backward compatibility issues

---

camel-k-core/support/src/main/java/org/apache/camel/k/listener/SourcesConfigurer.java
camel-k-core/support/src/test/java/org/apache/camel/k/listener/SourceConfigurerTest.java

Patch to avoid NPE such as in https://github.com/apache/camel-k/pull/2216
Ref #658
cc @nicolaferraro 
```release-note
NONE
```

fix(core): solve NPE when missing source type

---

.github/workflows/ci-build-camel-main.yaml
.github/workflows/ci-build.yml
.github/workflows/pr-validate.yml

This one has to be on main, so we have actions on camel-main
```release-note
NONE
```

Enable GH actions on camel-main branch

---

pom.xml

- includes Quarkus version bump to Quarkus 2.0.0.Alpha2
This one will fail checks and this is expected. Patches making this code compilable will follow this one. 
```release-note
NONE
```

Updated versions for Camel 3.10 and Camel Quarkus 1.9.x alignment

---

support/camel-k-itests-support/camel-k-itests-runtime-inspector/src/main/java/org/apache/camel/k/runtime/support/RuntimeInspector.java

Adjusted route output inspector to match API changes from Camel 3.10

---

pom.xml

Remove the camel-k-loader-groovy module from the main pom

---

itests/camel-k-itests-loader-groovy/pom.xml
itests/camel-k-itests-loader-java/pom.xml
itests/camel-k-itests-loader-js/pom.xml
itests/camel-k-itests-loader-jsh/pom.xml
itests/camel-k-itests-loader-kotlin/pom.xml
itests/camel-k-itests-loader-polyglot/pom.xml
itests/camel-k-itests-loader-xml/pom.xml
itests/camel-k-itests-loader-yaml/pom.xml

Fixed missing test dependency required from Camel 3.10

---

itests/camel-k-itests-kamelet-reify/pom.xml
itests/camel-k-itests-kamelet-reify/src/test/java/org/apache/camel/k/quarkus/kameletreify/KameletReifyTestResource.java

Converted the the KameletReifyTestResource to use Camel's test infra and fixes errors 
```release-note
NONE
```

Fix KameletReifyTestResource

---

camel-k-cron/impl/pom.xml
camel-k-cron/impl/src/test/java/org/apache/camel/k/cron/CronTest.java

Replace the deprecated YamlSourceLoaderDeserializerResolver on camel-k-cron tests

---

pom.xml

Version bump to Camel Quarkus 2.0.0-m1

---

itests/camel-k-itests-loader-groovy/pom.xml
itests/camel-k-itests-loader-groovy/src/main/java/org/apache/camel/k/loader/yaml/quarkus/Application.java
itests/camel-k-itests-loader-groovy/src/test/java/org/apache/camel/k/loader/yaml/quarkus/GroovyLoaderTest.java

Fixed GroovyLoader tests for Camel Quarkus 2.0.0 / Camel 3.10

---

support/camel-k-itests-support/camel-k-itests-runtime-inspector/src/main/java/org/apache/camel/k/runtime/support/RuntimeInspector.java

Fixed checkstyle violations

---

examples/cron/pom.xml
examples/groovy/pom.xml
examples/kamelets/pom.xml
examples/knative/pom.xml
examples/yaml/pom.xml
itests/camel-k-itests-cron/pom.xml
itests/camel-k-itests-kamelet-reify/pom.xml
itests/camel-k-itests-kamelet-reify/src/test/java/org/apache/camel/k/quarkus/kameletreify/KameletReifyTestResource.java
itests/camel-k-itests-kamelet/pom.xml
itests/camel-k-itests-knative-env-from-properties/pom.xml
itests/camel-k-itests-knative-env-from-registry/pom.xml
itests/camel-k-itests-knative-sinkbinding/pom.xml
itests/camel-k-itests-knative-source-groovy/pom.xml
itests/camel-k-itests-knative-source-yaml/pom.xml
itests/camel-k-itests-knative/pom.xml
itests/camel-k-itests-loader-java/src/main/java/org/apache/camel/k/loader/jsh/quarkus/Application.java
itests/camel-k-itests-loader-js/src/main/java/org/apache/camel/k/loader/js/quarkus/Application.java
itests/camel-k-itests-loader-jsh/src/main/java/org/apache/camel/k/loader/jsh/quarkus/JshApplication.java
itests/camel-k-itests-loader-kotlin/src/main/java/org/apache/camel/k/loader/kotlin/quarkus/Application.java
itests/camel-k-itests-loader-polyglot/pom.xml
itests/camel-k-itests-loader-polyglot/src/main/java/org/apache/camel/k/itests/polyglot/quarkus/Application.java
itests/camel-k-itests-loader-xml/src/main/java/org/apache/camel/k/loader/xml/quarkus/Application.java
itests/camel-k-itests-loader-yaml/pom.xml
itests/camel-k-itests-loader-yaml/src/main/java/org/apache/camel/k/loader/yaml/quarkus/Application.java
itests/camel-k-itests-runtime-yaml/pom.xml
itests/camel-k-itests-runtime/pom.xml
itests/camel-k-itests-webhook/pom.xml

itests and examples fixes for Camel Quarkus 2.0.0 + Camel 3.10

---

support/camel-k-runtime-bom/pom.xml

Fix runtime bom for 1.9

---

pom.xml
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java

Fixed Groovy loader for Camel Quarkus 2.x and Camel 3.10

---

itests/camel-k-itests-master/pom.xml

Fixed itests-master tests failures due to missing BouncyCastle deps

---

support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java

Fixed YAML Support with Camel 3.10.0

---

LICENSE
NOTICE

Rebase on Main

---

docs/modules/languages/pages/yaml.adoc

Remove preview flag from YAML docs

---

CHANGELOG.md
docs/modules/languages/pages/yaml.adoc
pom.xml
support/camel-k-runtime-bom/pom.xml

Rebase camel-main on main

---

pom.xml

Update to camel-quarkus 2.0.0-M2

---

pom.xml

Removed staging repository for Camel-Quarkus 2.0.0-M2

---

itests/camel-k-itests-knative-source-groovy/src/main/java/org/apache/camel/k/quarkus/it/knative/source/KnativeSourceApplication.java
itests/camel-k-itests-knative-source-java/src/main/java/org/apache/camel/k/quarkus/it/knative/source/KnativeSourceApplication.java
itests/camel-k-itests-knative-source-js/src/main/java/org/apache/camel/k/quarkus/it/knative/source/KnativeSourceApplication.java
itests/camel-k-itests-knative-source-xml/src/main/java/org/apache/camel/k/quarkus/it/knative/source/KnativeSourceApplication.java
itests/camel-k-itests-knative-source-yaml/src/main/java/org/apache/camel/k/quarkus/it/knative/source/KnativeSourceApplication.java
itests/camel-k-itests-webhook/src/main/java/org/apache/camel/k/quarkus/it/webhook/Application.java
support/camel-k-itests-support/camel-k-itests-runtime-inspector/src/main/java/org/apache/camel/k/runtime/support/RuntimeInspector.java

(chores) Avoid leaking resources during test execution

---

CHANGELOG.md
camel-k-core/api/src/main/java/org/apache/camel/k/SourceDefinition.java
camel-k-core/support/src/main/java/org/apache/camel/k/listener/SourcesConfigurer.java
camel-k-core/support/src/test/java/org/apache/camel/k/listener/SourceConfigurerTest.java
pom.xml

Sync camel-main with latest changes from main

---

pom.xml
support/camel-k-runtime-bom/pom.xml

Upgrade to camel-quarkus 2.0.0 and camel 3.11.0

---

pom.xml

Updates to use the development version of Camel Quarkus

---

pom.xml

deps: update camel-quarkus to v2.1.0

---

support/camel-k-runtime-bom/pom.xml

build(deps): bump apache from 23 to 24

---

docs/modules/languages/pages/yaml.adoc

Useful for troubleshooting or checking how to use the YAML DSL.
```release-note
NONE
```

Link to spec

---

components/camel-knative/camel-knative/src/generated/resources/org/apache/camel/component/knative/knative.json
pom.xml

fix: use the quarkus catalog instead of the vanilla one

---

components/camel-cloudevents/pom.xml

chore(deps): remove useless test dependency

---

docs/antora.yml

chore(doc): Add 1.7.x documentation

---

pom.xml

chore: remove staging maven repo

---

components/camel-knative/camel-knative/src/generated/resources/org/apache/camel/component/knative/knative.json
pom.xml
support/camel-k-test/pom.xml
support/camel-k-test/src/main/java/org/apache/camel/k/test/AvailablePortFinder.java

deps: remove log4j as it is not needed

---

pom.xml

deps: upgrade camel-quarkus to v2.6.0

---

camel-k-knative/impl/src/main/java/org/apache/camel/k/knative/customizer/KnativeSinkBindingContextCustomizer.java
components/camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java

Closes #764
```release-note
fix(knative): use object name when events endpoints
```

fix(knative): use object name when events endpoints

---

pom.xml

Point to the latest tag in scm pom section

---

docs/antora.yml

Set up for new camel-k 1.8.x doc version.

set camel-k docs version

---

pom.xml
support/camel-k-maven-plugin/pom.xml

```release-note
chore(deps): let transitive maven-core dependency
```

chore(deps): let transitive maven-core dependency

---

camel-k-core/support/src/main/java/org/apache/camel/k/support/SourcesSupport.java

chore: use isEmpty() instead of size() == 0

---

pom.xml

Removed staging repositories for Camel-quarkus 2.8.0-M1

---

pom.xml

Remove staging repositories for Camel Quarkus 2.8.0

---

README.adoc
itests/camel-k-itests-loader-groovy/pom.xml
itests/camel-k-itests-runtime/pom.xml
pom.xml
scripts/bump.sh
support/camel-k-maven-plugin/pom.xml
support/camel-k-runtime-bom/pom.xml

A script to automate the major dependency upgrades.
```release-note
feat(deps): script to bump dependencies
```

feat(deps): script to bump dependencies

---

pom.xml
support/camel-k-runtime-bom/pom.xml

as required by https://camel.apache.org/camel-quarkus/next/user-guide/dependency-management.html
```release-note
chore(deps): Camel Quarkus dependency management
```

chore(deps): Camel Quarkus dependency management

---

pom.xml
scripts/bump.sh

```release-note
chore(deps): move Quarkus native image into a property
```

chore(deps): move Quarkus native image into a property

---

docs/modules/languages/pages/yaml.adoc

chore: fix 404

---

itests/camel-k-itests-master/pom.xml
pom.xml

Align Camel 3.18 dependencies

---

support/camel-k-runtime-bom/pom.xml

Update to use the bom for Quarkus 2.11.0

---

.github/workflows/automatic-changelog-update.yml
.github/workflows/backport.yml
.github/workflows/ci-build-camel-main.yaml
.github/workflows/ci-build.yml
.github/workflows/pr-validate.yml

(chores) ci: update checkout actions to v3

---

support/camel-k-runtime-bom/pom.xml

Fixed an invalid resume api dependency reference in the bom

---

pom.xml
scripts/bump.sh

Ref https://github.com/apache/camel-k/issues/3560
```release-note
NONE
```

fix: set quarkus core version to 2.11.2.Final

---

camel-k-core/support/src/main/java/org/apache/camel/k/support/SourcesSupport.java

Workaround reintroduced to fix a Camel regression as specified in https://github.com/apache/camel-k/issues/3560#issuecomment-1230042204
Ref #3560
```release-note
NONE
```

fix(core): Error handler regression

---

.github/workflows/ci-build.yml

chore(ci): extend check on release branches

---

.github/workflows/ci-build.yml

[Backport] chore(ci): extend check on release branch

---

camel-k-core/deployment/pom.xml
pom.xml

Upgrade to Camel Quarkus 2.13.0

---

pom.xml
support/camel-k-runtime-bom/pom.xml

Prepare for 1.15.0

---

pom.xml
support/camel-k-runtime-bom/pom.xml

Point to Quarkus Platform 2.13.0.Final

---

.github/workflows/ci-build.yml

and push also sources and m2 (required by Camel K)
```release-note
feat(ci): publish snapshot on release branches
```

feat(ci): publish snapshot on release branches

---

.github/workflows/ci-build.yml

fix(ci): proper directory

---

.github/workflows/ci-build.yml
distribution/pom.xml

fix(ci): using a profile for distribution artifact

---

camel-k-core/support/pom.xml
itests/camel-k-itests-cron/pom.xml
itests/camel-k-itests-webhook/pom.xml
pom.xml

[Backport] chore: dependency cleaning

---

itests/camel-k-itests-cron/pom.xml
itests/camel-k-itests-loader-polyglot/pom.xml
itests/camel-k-itests-loader-yaml/pom.xml
pom.xml
support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-runtime-bom/pom.xml

Align to deps coming from next release 1.15.2 even on main

---

itests/camel-k-itests-cron/pom.xml
itests/camel-k-itests-loader-polyglot/pom.xml
itests/camel-k-itests-loader-yaml/pom.xml
pom.xml
support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-runtime-bom/pom.xml

Preparing for release 1.15.2

---

distribution/src/main/assemblies/repository.xml

[backport] fix(ci): keep version artifact only

---

pom.xml

Remove duplicate maven-assembly-plugin-version property from pom.xml

---

pom.xml
scripts/bump.sh
support/camel-k-runtime-bom/pom.xml

Have a separate property to control quarkus-camel-bom in case of CVE or any other fix to apply
```release-note
feat(deps): split quarkus-camel-bom
```

feat(deps): split quarkus-camel-bom

---

pom.xml
scripts/bump.sh
support/camel-k-runtime-bom/pom.xml

Have a separate property to control quarkus-camel-bom in case of CVE or any other fix to apply
```release-note
NONE
```

[1.16.x] feat(deps): split quarkus-camel-bom

---

pom.xml
scripts/bump.sh
support/camel-k-runtime-bom/pom.xml

Have a separate property to control quarkus-camel-bom in case of CVE or any other fix to apply
```release-note
NONE
```

[1.15.x] feat(deps): split quarkus-camel-bom

---

camel-k-resume-kafka/impl/src/main/java/org/apache/camel/k/resume/kafka/KafkaResumeFactory.java
pom.xml
support/camel-k-runtime-bom/pom.xml

```release-note
Upgrade to Camel 3.20.1, Quarkus 2.16.0.Final and Camel-Quarkus 2.16.0
```
Fixes #950 and related to #951 
Still waiting for Quarkus platform 2.16.0.Final release.

Prepare release 1.17.0

---

support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java
support/camel-k-runtime-bom/pom.xml

Move jolokia exclusions from generate-catalog maven plugin to the camel-k-runtime-bom/pom.xml

---

pom.xml
support/camel-k-maven-logging/pom.xml
support/camel-k-test/pom.xml

```release-note
feat(ci): add a check to avoid duplicate dependencies
```

feat(ci): add a check to avoid duplicate dependencies

---

pom.xml
support/camel-k-maven-logging/pom.xml
support/camel-k-test/pom.xml

[Backport 1.17.x] feat(ci): add a check to avoid duplicate dependencies

---

pom.xml
support/camel-k-maven-logging/pom.xml
support/camel-k-test/pom.xml

[Backport 1.15.x] feat(ci): add a check to avoid duplicate dependencies

---

pom.xml
support/camel-k-runtime-bom/pom.xml

```release-note
chore(deps): Camel Quarkus 2.13.2
```

chore(deps): Camel Quarkus 2.13.2

---

pom.xml

[backport 1.17] chore(ci): split maven version property

---

pom.xml

[backport 1.15] chore(ci): split maven version property

---

camel-k-core/deployment/pom.xml
camel-k-core/support/pom.xml
camel-k-runtime/deployment/pom.xml
camel-k-runtime/runtime/pom.xml
itests/camel-k-itests-core/pom.xml
itests/camel-k-itests-loader-js/pom.xml
itests/camel-k-itests-loader-polyglot/pom.xml
itests/camel-k-itests-loader-xml/pom.xml
itests/camel-k-itests-loader-yaml/pom.xml

[Backport 1.15.x] chore(deps): camel-quarkus-kubernetes

---

README.adoc
release.adoc

Ref https://github.com/apache/camel-k/issues/4282
```release-note
doc: Camel K 2.0 independent release process
```

doc: Camel K 2.0 independent release process

---

camel-k-cron/impl/src/main/java/org/apache/camel/k/cron/CronSourceLoaderInterceptor.java

Closes https://github.com/apache/camel-k/issues/4343
```release-note
fix(cron): gracefully stop when all exchanges are processed
```

fix(cron): gracefully stop when all exchanges are processed

---

camel-k-cron/impl/src/main/java/org/apache/camel/k/cron/CronSourceLoaderInterceptor.java

Closes https://github.com/apache/camel-k/issues/4343
```release-note
NONE
```

[backport 1.17.x] fix(cron): gracefully stop when all exchanges are processed

---

release.adoc

```release-note
chore: update release procedure
```

chore: update release procedure

---

release.adoc

```release-note
chore(doc): polished release notes
```

chore(doc): polished release notes

---

.github/workflows/nightly-automatic-updates.yml
scripts/release-branch.sh

fix(ci): tasks name

---

.github/actions/automatic-updates/atcion.yaml

fix(ci): nightly auto updates compatibility

---

.gitignore
examples/cron/pom.xml
examples/groovy/pom.xml
examples/java/pom.xml
examples/js/pom.xml
examples/kafka-source-s3/pom.xml
examples/kamelets-discovery/pom.xml
examples/kamelets/pom.xml
examples/knative/pom.xml
examples/kotlin/pom.xml
examples/xml/pom.xml
examples/yaml/pom.xml
itests/pom.xml
pom.xml
support/camel-k-runtime-bom/pom.xml

Define a maven group for the quarkus maven plugin

---

.github/workflows/ci-build.yml
.github/workflows/pr-validate.yml
.mvn/wrapper/maven-wrapper.properties
pom.xml
support/camel-k-runtime-bom/pom.xml

Also update maven version
```release-note
NONE
```

Update to Java 17 as in CEQ 3

---

support/camel-k-catalog-model/src/main/java/org/apache/camel/k/catalog/model/Artifact.java
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

Adds some capabilities present in camel-k and their dependencies.
```release-note
NONE
```

Add more capabilities and their dependencies

---

itests/camel-k-itests-loader-kotlin/src/test/java/org/apache/camel/k/loader/kotlin/quarkus/KotlinLoaderTest.java

```release-note
chore(tests): re enable kotlin test
```

chore(tests): re enable kotlin test

---

camel-k-core/runtime/pom.xml

```release-note
chore(deps): remove non required dependency
```

chore(deps): remove non required dependency

---

pom.xml
support/camel-k-runtime-bom/pom.xml

```release-note
chore(deps): bump quarkus platform
```

chore(deps): bump quarkus platform

---

examples/yaml/data/routes.yaml

Backport of https://github.com/apache/camel-k-runtime/pull/1090
```release-note
NONE
```

[Backport 2.16.x] fix(examples): Fix yaml data route

---

pom.xml
support/camel-k-maven-plugin/pom.xml
support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java
support/camel-k-maven-plugin/src/main/resources/app.properties

Ref apache/camel-k#4703
```release-note
NONE
```

feat: Add jib plugins versions to catalog runtime metadata

---

pom.xml

```release-note
Add SBOM to the release process
```
Fixes #1110

Add SBOM to the release process

---

pom.xml

```release-note
chore: upgrade native builder image
```

chore: upgrade native builder image

---

support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

Ref https://github.com/apache/camel-k/issues/4990
```release-note
fix(catalog): quarkus jaxb dependency
```

fix(catalog): quarkus jaxb dependency

---

pom.xml
support/camel-k-runtime-bom/pom.xml

```release-note
Update quarkus platform to 3.2.10
```

Update quarkus platform to 3.2.10

---

docs/package.json
docs/yarn.lock

```release-note
fix(docs): update dependencies
```

fix(docs): update dependencies

---

pom.xml
support/camel-k-catalog-model/src/main/java/org/apache/camel/k/catalog/model/CamelCapability.java

```release-note
fix(catalog): compatibility Camel K < 2.2.0
```

fix(catalog): compatibility Camel K < 2.2.0

---

.github/workflows/nightly-automatic-updates.yml

fix(ci): keep updating 3.6.x

---

docs/modules/languages/pages/yaml.adoc

Fix wrong link
```release-note
NONE
```

Fix wrong link

---

camel-k-master/deployment/pom.xml
camel-k-master/impl/pom.xml
camel-k-master/impl/src/main/java/org/apache/camel/k/master/MasterContextCustomizer.java
camel-k-master/runtime/pom.xml
support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

* Add missing Kubernetes cluster service module
* Update configuration of module
* Fix properties customization for camel-k-master
Ref apache/camel-k#5746
```release-note
fix: Fix master addon configuration
```

fix(5746): Fix master addon configuration

---

support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

Closes https://github.com/apache/camel-k/issues/5837
```release-note
NONE
```

feat: add a deprecation metadata to languages no longer supported

---

pom.xml
support/camel-k-runtime-bom/pom.xml

```release-note
chore: bump Quarkus platform to 3.15.1
```

chore: bump Quarkus platform to 3.15.1

---

support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

```release-note
feat(catalog): change micrometer dependencies
```

feat(catalog): change micrometer dependencies

---

scripts/sync_cq.sh

```release-note
fix(ci): nightly update action
```

fix(ci): nightly update action

---

camel-k-core/support/src/test/java/org/apache/camel/k/listener/PropertiesFunctionsConfigurerTest.java

fix(core) failing test

---

pom.xml
support/camel-k-runtime-bom/pom.xml

chore(deps): bump Quarkus platform to 3.15.4
