apache/camel-k-runtime

camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEnvironment.java
camel-knative/src/test/java/org/apache/camel/component/knative/KnativeComponentTest.java
camel-knative/src/test/resources/environment.json

Fixes #19
Fixes apache/camel-k#506

Default service definition not taken into account

---

camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor_2_x.java
camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor_3_x.java
camel-k-runtime-bom/pom.xml
camel-k-runtime-core/src/main/java/org/apache/camel/k/Runtime.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/listener/RoutesConfigurer.java
camel-k-runtime-core/src/main/resources/META-INF/services/org.apache.camel.k.Runtime$Listener
camel-k-runtime-health/pom.xml
camel-k-runtime-health/src/main/java/org/apache/camel/k/health/HealthConfigurer.java
camel-k-runtime-health/src/main/java/org/apache/camel/k/health/HealthEndpoint.java
camel-k-runtime-health/src/main/resources/META-INF/LICENSE.txt
camel-k-runtime-health/src/main/resources/META-INF/NOTICE.txt
camel-k-runtime-health/src/main/resources/META-INF/services/org.apache.camel.k.Runtime$Listener
camel-k-runtime-health/src/test/java/org/apache/camel/k/health/HealthMain.java
camel-k-runtime-health/src/test/resources/log4j2-test.xml
camel-k-runtime-jvm/src/main/java/org/apache/camel/k/jvm/ApplicationRuntime.java
pom.xml

Add runtime health endpoint

---

.travis.yml
camel-k-adapter-camel-2/src/main/java/org/apache/camel/k/adapter/DefaultRegistry.java
camel-k-adapter-camel-2/src/main/java/org/apache/camel/k/adapter/Main.java
camel-k-adapter-camel-2/src/main/java/org/apache/camel/k/adapter/Registry.java
camel-k-adapter-camel-2/src/main/java/org/apache/camel/k/adapter/Resources.java
camel-k-adapter-camel-2/src/main/java/org/apache/camel/k/adapter/Routes.java
camel-k-adapter-camel-3/src/main/java/org/apache/camel/k/adapter/DefaultRegistry.java
camel-k-adapter-camel-3/src/main/java/org/apache/camel/k/adapter/Main.java
camel-k-adapter-camel-3/src/main/java/org/apache/camel/k/adapter/Registry.java
camel-k-adapter-camel-3/src/main/java/org/apache/camel/k/adapter/Routes.java
camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateRestXML.java
camel-k-maven-plugin/src/test/java/org/apache/camel/k/tooling/maven/processors/CataloProcessor2Test.java
camel-k-maven-plugin/src/test/java/org/apache/camel/k/tooling/maven/processors/CataloProcessor3Test.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/InMemoryRegistry.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/Runtime.java
camel-k-runtime-groovy/src/test/groovy/org/apache/camel/k/groovy/LoaderTest.groovy
camel-k-runtime-jvm/src/main/java/org/apache/camel/k/jvm/ApplicationRuntime.java
camel-k-runtime-jvm/src/main/java/org/apache/camel/k/jvm/loader/XmlLoader.java
camel-k-runtime-jvm/src/test/java/org/apache/camel/k/jvm/RoutesLoadersCommonTest.java
camel-k-runtime-jvm/src/test/java/org/apache/camel/k/jvm/RoutesLoadersTest.java
camel-k-runtime-kotlin/src/test/kotlin/org/apache/camel/k/kotlin/LoaderTest.kt
camel-k-runtime-spring-boot/src/main/java/org/apache/camel/k/spring/boot/ApplicationAutoConfiguration.java
camel-k-runtime-yaml/src/test/java/org/apache/camel/k/yaml/RoutesLoaderTest.java
camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpComponent.java
camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpMain.java
pom.xml

this supersede #39
I think we should discuss the option to drop support to camel 2.x when 3.x will hit its first release but till that date we should make some effort to support both.
@davsclaus @nicolaferraro @oscerd @astefanutti, what do you think ?

Suport for camel 3.0.0-M2 and 2.21.x

---

camel-k-adapter-camel-2/pom.xml
camel-k-adapter-camel-3/pom.xml
camel-k-maven-plugin/pom.xml
camel-k-runtime-bom/pom.xml
camel-k-runtime-core/pom.xml
camel-k-runtime-groovy/pom.xml
camel-k-runtime-health/pom.xml
camel-k-runtime-jvm/pom.xml
camel-k-runtime-kotlin/pom.xml
camel-k-runtime-spring-boot-layout/pom.xml
camel-k-runtime-spring-boot/pom.xml
camel-k-runtime-yaml/pom.xml
camel-knative-http/pom.xml
camel-knative/pom.xml
distribution/pom.xml
pom.xml

Preparing to cut a new 0.3.2 release.

Rollback to 0.3.2-SNAPSHOT and re-enable missing module

---

camel-k-runtime-kotlin/src/main/kotlin/org/apache/camel/k/kotlin/KotlinRoutesLoader.kt
camel-k-runtime-kotlin/src/main/kotlin/org/apache/camel/k/kotlin/dsl/IntegrationConfiguration.kt
camel-k-runtime-kotlin/src/test/kotlin/org/apache/camel/k/kotlin/dsl/IntegrationTest.kt
camel-k-runtime-kotlin/src/test/resources/routes-with-error-handler.kts
camel-k-runtime-kotlin/src/test/resources/routes-with-rest.kts

- add missing methods from route builder / builder support
- add initial support for kotlin auto completion in idea

improve kotlin support

---

camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java
camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java
camel-k-maven-plugin/src/test/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3Test.java
camel-k-runtime-core/pom.xml
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/PropertiesSupport.java
camel-k-runtime-examples/camel-k-runtime-example-health/pom.xml
camel-k-runtime-examples/camel-k-runtime-example-servlet/pom.xml
camel-k-runtime-examples/camel-k-runtime-example-yaml/pom.xml
camel-k-runtime-groovy/pom.xml
camel-k-runtime-health/pom.xml
camel-k-runtime-jvm/pom.xml
camel-k-runtime-knative/pom.xml
camel-k-runtime-kotlin/pom.xml
camel-k-runtime-servlet/pom.xml
camel-k-runtime-yaml/pom.xml
camel-k-runtime-yaml/src/main/java/org/apache/camel/k/yaml/parser/SetHeaderStepParser.java
camel-k-runtime-yaml/src/main/java/org/apache/camel/k/yaml/parser/SetPropertyStepParser.java
camel-k-runtime-yaml/src/main/java/org/apache/camel/k/yaml/parser/StepParserSupport.java
camel-k-runtime-yaml/src/test/groovy/org/apache/camel/k/yaml/parser/SetHeaderTest.groovy
camel-k-runtime-yaml/src/test/groovy/org/apache/camel/k/yaml/parser/SetPropertyTest.groovy
camel-knative-http/pom.xml
camel-knative/pom.xml
pom.xml

Update to camel 3.0.0-M4

---

README.adoc

it allows to see immediately the status of the master build and know
where it is built
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Provide Travis CI badge

---

camel-k-runtime-examples/camel-k-runtime-example-health/pom.xml
camel-k-runtime-examples/camel-k-runtime-example-servlet/pom.xml
camel-k-runtime-examples/camel-k-runtime-example-yaml/pom.xml

After the recent refactor of camel-k-runtime,  the main class name of camel-k-runtime-main was changed which breaked the running of camel-k-runtime-examples with 'mvn exec:java'.

Fix the camel-k-runtime-example running issue

---

camel-k-loader-js/pom.xml
camel-k-loader-js/src/main/java/org/apache/camel/k/loader/js/JavaScriptRoutesLoader.java
camel-k-loader-js/src/test/java/org/apache/camel/k/loader/js/dsl/IntegrationTest.java
camel-k-loader-js/src/test/resources/routes-with-processors.js

Lambda processor doesn't work with JS routes

---

camel-knative-http/pom.xml
camel-knative/pom.xml
camel-knative/src/main/java/org/apache/camel/component/knative/KnativeComponent.java
camel-knative/src/main/java/org/apache/camel/component/knative/KnativeConfiguration.java
camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java
camel-knative/src/test/java/org/apache/camel/component/knative/KnativeComponentTest.java

You cna configure the transport by using properties with 'transport.' as 
prefix, as example, to configure a custom header filter strategy, one 
can define the endpoint like:
knative:endpoint/myEndpoint?transport.headerFilterStrategy=#myFilterStrategy
Fixes #118

Knative component filters out all headers

---

camel-k-loader-knative/pom.xml
camel-k-loader-knative/src/main/java/org/apache/camel/k/loader/knative/KnativeSourceRoutesLoader.java
camel-k-loader-knative/src/main/resources/META-INF/services/org/apache/camel/k/loader/knative-source
camel-k-loader-knative/src/main/resources/META-INF/services/org/apache/camel/k/loader/knative-source-groovy
camel-k-loader-knative/src/main/resources/META-INF/services/org/apache/camel/k/loader/knative-source-java
camel-k-loader-knative/src/main/resources/META-INF/services/org/apache/camel/k/loader/knative-source-js
camel-k-loader-knative/src/main/resources/META-INF/services/org/apache/camel/k/loader/knative-source-kts
camel-k-loader-knative/src/main/resources/META-INF/services/org/apache/camel/k/loader/knative-source-xml
camel-k-loader-knative/src/main/resources/META-INF/services/org/apache/camel/k/loader/knative-source-yaml
camel-k-loader-knative/src/test/java/org/apache/camel/k/loader/knative/KnativeSourceRoutesLoaderTest.java
camel-k-loader-knative/src/test/resources/log4j2-test.xml
camel-k-loader-knative/src/test/resources/routes.groovy
camel-k-loader-knative/src/test/resources/routes.java
camel-k-loader-knative/src/test/resources/routes.js
camel-k-loader-knative/src/test/resources/routes.kts
camel-k-loader-knative/src/test/resources/routes.xml
camel-k-loader-knative/src/test/resources/routes.yaml
camel-k-runtime-bom/pom.xml
camel-k-runtime-core/src/main/java/org/apache/camel/k/Source.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/RuntimeSupport.java
camel-k-runtime-knative/pom.xml
camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEnvironment.java
pom.xml
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java

This new loader enrich terminates a route with an uri like:
knative://endpoint/{{env:KNATIVE_SINK:synk}}
It does not support sources that define more than one route.

knative: add custom loader for sources

---

pom.xml
tooling/camel-k-maven-plugin/pom.xml
tooling/camel-k-maven-plugin/src/it/generate-catalog/pom.xml
tooling/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java
tooling/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/model/crd/CamelCatalogSpec.java

Include camel-k-runtime version in camel-catalog

---

tooling/camel-k-maven-plugin/src/it/generate-catalog/pom.xml
tooling/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy

https://github.com/apache/camel-k-runtime/issues/164

Fix issue 164 to update the runtime version

---

docs/modules/languages/pages/java.adoc

If you try to run this example you will get a compilation error "class Sample is public, should be declared in a file named Sample.java". To solve this and to be consistent to the other language examples, the class should be renamed to Example.

Classname does not match the Filename.

---

camel-k-loader-yaml/camel-k-loader-yaml-common/src/main/java/org/apache/camel/k/loader/yaml/parser/ErrorHandlerStepParser.java
camel-k-loader-yaml/camel-k-loader-yaml-common/src/main/java/org/apache/camel/k/loader/yaml/spi/StepParser.java
camel-k-loader-yaml/camel-k-loader-yaml-common/src/main/java/org/apache/camel/k/loader/yaml/spi/StepParserSupport.java
camel-k-loader-yaml/camel-k-loader-yaml/src/main/java/org/apache/camel/k/loader/yaml/YamlSourceLoader.java
camel-k-loader-yaml/camel-k-loader-yaml/src/test/groovy/org/apache/camel/k/loader/yaml/RoutesTest.groovy
camel-k-loader-yaml/camel-k-loader-yaml/src/test/groovy/org/apache/camel/k/loader/yaml/TestSupport.groovy
camel-k-loader-yaml/camel-k-loader-yaml/src/test/groovy/org/apache/camel/k/loader/yaml/parser/ErrorHandlerTest.groovy
camel-k-loader-yaml/camel-k-loader-yaml/src/test/resources/routes/RoutesTest_errorHandler.yaml
tooling/camel-k-annotations/src/main/java/org/apache/camel/k/annotation/yaml/YAMLNodeDefinition.java

Fixes #339
There some limitations now as the underlying builders do not provide
`xyzRef` fields so it is not actually possible to add processors like
`onExceptionOccurred` but those capabilities are present in the xml
DSL so we may need to revisit Error Handler support to add the same
level of integration.

yaml-loader: add support for error handler

---

camel-k-loader-java/src/main/java/org/apache/camel/k/loader/java/JavaSourceLoader.java
camel-k-loader-java/src/test/java/org/apache/camel/k/loader/java/RoutesLoaderTest.java
camel-k-loader-java/src/test/resources/MyRoutesWithNestedTypes.java
camel-k-main/camel-k-runtime-main/src/main/java/org/apache/camel/k/main/ApplicationRuntime.java
camel-k-quarkus/camel-k-quarkus-core/deployment/src/main/java/org/apache/camel/k/core/quarkus/deployment/DeploymentProcessor.java
camel-k-quarkus/camel-k-quarkus-core/runtime/src/main/java/org/apache/camel/k/core/quarkus/RuntimeRecorder.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-core/src/main/java/org/apache/camel/k/core/quarkus/deployment/Application.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-core/src/test/java/org/apache/camel/k/core/quarkus/deployment/ExtensionTest.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/CompositeClassloader.java

Create a CompositeClassloader and set is as Camel's ApplicationClassloader

---

camel-k-loader-yaml/camel-k-loader-yaml/pom.xml
camel-k-loader-yaml/camel-k-loader-yaml/src/test/groovy/org/apache/camel/k/loader/yaml/RoutesValidationTest.groovy
camel-k-loader-yaml/camel-k-loader-yaml/src/test/resources/routes/RoutesTest_aggregator.yaml
pom.xml

Fixes #387
Note that there's no '*.camelk.yaml' files

Include a test collecting all *.camelk.yaml files in the repository and validating it against the yaml schema

---

.github/workflows/pr-validate.yml

build(ci): Ignore some paths on the PR validate workflow

---

camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-kotlin/pom.xml
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-kotlin/src/main/java/org/apache/camel/k/loader/kotlin/quarkus/Application.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-kotlin/src/main/resources/application.properties
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-kotlin/src/test/java/org/apache/camel/k/loader/kotlin/quarkus/KotlinLoaderTest.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-loader-kotlin/src/test/resources/routes.kts
camel-k-quarkus/camel-k-quarkus-itests/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-kotlin/deployment/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-kotlin/pom.xml
camel-k-quarkus/camel-k-quarkus-loader-kotlin/runtime/pom.xml
camel-k-quarkus/pom.xml
examples/camel-k-runtime-example-quarkus-kotlin/pom.xml

Test is currently disabled because of https://github.com/quarkusio/quarkus/issues/11549
```release-note
NONE
```

loaders: add itest for kotlin on quarkus

---

.github/workflows/pr-validate.yml
camel-k-main/camel-k-runtime-main/src/test/java/org/apache/camel/k/main/support/RuntimeTestSupport.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-kamelet/src/main/java/org/apache/camel/k/quarkus/kamelet/deployment/Application.java
camel-k-quarkus/camel-k-quarkus-itests/camel-k-quarkus-itests-kamelet/src/test/java/org/apache/camel/k/quarkus/kamelet/deployment/KameletTest.java
camel-k-runtime-core/src/main/java/org/apache/camel/k/support/SourcesSupport.java
camel-kamelet/src/generated/resources/org/apache/camel/component/kamelet/kamelet.json
camel-kamelet/src/main/java/org/apache/camel/component/kamelet/Kamelet.java
camel-kamelet/src/main/java/org/apache/camel/component/kamelet/KameletEndpoint.java
camel-knative/camel-knative/src/generated/resources/org/apache/camel/component/knative/knative.json
pom.xml

Fix PMD and checkstyle violations

---

camel-k-loader-yaml/camel-k-loader-yaml-common/src/main/java/org/apache/camel/k/loader/yaml/parser/BeansStepParser.java
camel-k-loader-yaml/camel-k-loader-yaml/src/generated/resources/camel-yaml-dsl.json
camel-k-loader-yaml/camel-k-loader-yaml/src/test/groovy/org/apache/camel/k/loader/yaml/RoutesTest.groovy
camel-k-loader-yaml/camel-k-loader-yaml/src/test/resources/routes/RoutesTest_beans.yaml

Fixes #376
```release-note
NONE
```

[yaml] support for configuring beans with the yaml dsl

---

.github/asf-deploy-settings.xml
.github/workflows/ci-build.yml

Ref https://issues.apache.org/jira/browse/INFRA-20846
```release-note
NONE
```

build: deploy to ASF snapshots from GitHub Actions

---

components/camel-kamelet/pom.xml
components/camel-kamelet/src/main/java/org/apache/camel/component/kamelet/KameletComponent.java
components/camel-kamelet/src/test/java/org/apache/camel/component/kamelet/KameletPropertiesTest.java

kamelet: ensure properties are correctly propagated to the route template engine

---

camel-k-core/api/src/main/java/org/apache/camel/k/Runtime.java
camel-k-core/api/src/main/java/org/apache/camel/k/SourceLoader.java
camel-k-core/support/src/main/java/org/apache/camel/k/listener/PropertiesConfigurer.java
camel-k-core/support/src/main/java/org/apache/camel/k/support/DelegatingRuntime.java
camel-k-core/support/src/main/java/org/apache/camel/k/support/PropertiesSupport.java
camel-k-core/support/src/main/java/org/apache/camel/k/support/RuntimeSupport.java
camel-k-runtime/runtime/src/main/java/org/apache/camel/k/quarkus/Application.java
camel-k-runtime/runtime/src/main/java/org/apache/camel/k/quarkus/ApplicationConfigSourceProvider.java
itests/camel-k-itests-runtime/src/main/java/org/apache/camel/k/quarkus/it/Application.java
itests/camel-k-itests-runtime/src/test/java/org/apache/camel/k/quarkus/it/RuntimeTest.java
itests/camel-k-itests-runtime/src/test/resources/conf.d/003/flat-property

Leveragte MP Config to load application and user properties

---

components/camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
components/camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/ce/AbstractCloudEventProcessor.java

Fix https://github.com/apache/camel-k/issues/1813
Switch to using route id as source (which is computed after kamelet name, in case of kamelet consumer).
Wdyt @lburgazzoli ?
```release-note
NONE
```

Fix https://github.com/apache/camel-k/issues/1813

---

components/camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
components/camel-knative/camel-knative/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java

Fix #536
```release-note
NONE
```

Fix #536: enable knative:event endpoints without path

---

camel-k-loader-yaml/impl-common/src/main/java/org/apache/camel/k/loader/yaml/support/StepParserSupport.java
components/camel-kamelet-reify/src/generated/resources/org/apache/camel/component/kameletreify/kamelet-reify.json
components/camel-kamelet/src/generated/resources/org/apache/camel/component/kamelet/kamelet.json
components/camel-knative/camel-knative/src/generated/resources/org/apache/camel/component/knative/knative.json
itests/camel-k-itests-kamelet/src/main/java/org/apache/camel/k/quarkus/it/Application.java
itests/camel-k-itests-kamelet/src/test/java/org/apache/camel/k/quarkus/it/RuntimeTest.java
itests/camel-k-itests-kamelet/src/test/resources/routes.properties
itests/camel-k-itests-kamelet/src/test/resources/routes/process-params.yaml

Fixes #581
Fixes https://github.com/apache/camel-k/issues/1882
```release-note
NONE
```

Cannot use kamelets in yaml integrations

---

support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

prerequisite for https://github.com/apache/camel-k/pull/1931.
I set the itests to use fast-jar. Not sure if that's entirely necessary, so I can drop that commit if necessary.
```release-note
NONE
```

Support fast-jar packaging for quarkus

---

.github/workflows/ci-build-camel-master.yaml
.github/workflows/ci-build.yml

Github actions: Do not persist credentials for Checkout action

---

support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

When the fix for https://github.com/quarkusio/quarkus/issues/14583 is available via camel-quarkus I'll redo this change.

Revert "Support fast-jar packaging for quarkus"

---

components/camel-kamelet-reify/pom.xml
itests/camel-k-itests-kamelet-reify/pom.xml

Ref #626
With this PR we should fix the PR actions failures.
```release-note
NONE
```

fix(test): bump testcontainers to 1.5.1

---

support/camel-k-runtime-bom/pom.xml

Fix #655 
```release-note
NONE
```

Missing camel-k-kamelet-reify version while building kamelet binding

---

examples/cron/README.md
examples/cron/pom.xml
examples/groovy/pom.xml
examples/java/README.md
examples/java/pom.xml
examples/js/pom.xml
examples/kafka-source-s3/README.md
examples/kafka-source-s3/pom.xml
examples/kamelets/pom.xml
examples/knative/pom.xml
examples/kotlin/pom.xml
examples/xml/pom.xml
examples/yaml/pom.xml

Based on [comment](https://github.com/apache/camel-k-runtime/pull/643#issuecomment-804727535) - adding the option to run the examples using:
`mvn clean compile quarkus:dev`
@lburgazzoli there seems to be a problem with the java example, which doesn't seem to run using the above mentioned command - there seems to be a problem with classloading, the problem is:
```
2021-04-16 13:51:22,023 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (Quarkus Main Thread) Failed to start application: org.apache.camel.RuntimeCamelException: org.joor.ReflectException: Compilation error: /MyRoutes.java:17: error: package org.apache.camel.builder does not exist
import org.apache.camel.builder.RouteBuilder;
^
/MyRoutes.java:19: error: cannot find symbol
public class MyRoutes extends RouteBuilder {
^
symbol: class …
```

Add quarkus:dev option for running the examples

---

.github/workflows/ci-build-camel-main.yaml

Temporarily disable building Camel Main on camel-main branch due to alignment with Camel Quarkus 1.9
```release-note
NONE
```

GH action fixes

---

.github/workflows/ci-build-camel-main.yaml

Temporarily disable building Camel Main on camel-main branch due to alignment with Camel Quarkus 1.9

---

.github/workflows/ci-build-camel-main.yaml
.github/workflows/ci-build.yml
.github/workflows/pr-validate.yml
pom.xml

Camel Quarkus bumped to 2.x after aligning w/ Camel 3.10. So, adjusting it accordingly
```release-note
NONE
```

Adjust to use latest Camel Quarkus after they aligned w/ Camel 3.10

---

camel-k-knative/consumer/deployment/src/main/java/org/apache/camel/k/quarkus/knative/consumer/deployment/KnativeConsumerProcessor.java

Fixed VertxWebRouterBuildItem router call modified in Vert.x 4

---

support/camel-k-catalog/pom.xml
support/camel-k-maven-plugin/src/it/generate-catalog/pom.xml
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/support/CatalogProcessor.java
support/camel-k-maven-plugin/src/test/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3Test.java

Work-around #677 by excluding certain components from the catalog until apache/camel-quarkus#2661 is implemented
Just a temporary work-around, but let's wait for the discussions on Camel Quarkus before going this route.
```release-note
NONE
```

(Do not merge) Allow excluding components from the catalog.

---

.github/workflows/ci-build-camel-main.yaml

Disable an unused step until we fully align to Camel Quarkus main
```release-note
NONE
```

Temporarily disable building Camel Quarkus on GH actions

---

camel-k-core/api/src/main/java/org/apache/camel/k/SourceDefinition.java
camel-k-core/support/src/main/java/org/apache/camel/k/listener/SourcesConfigurer.java
camel-k-core/support/src/test/java/org/apache/camel/k/listener/SourceConfigurerTest.java

Setting any empty SourceType as a source.
Closes #658
Closes https://github.com/apache/camel-k/issues/2223
```release-note
NONE
```

fix(core): default SourceType as source

---

camel-k-core/support/src/test/java/org/apache/camel/k/listener/PropertiesFunctionsConfigurerTest.java
camel-k-core/support/src/test/java/org/apache/camel/k/listener/SourceConfigurerTest.java
camel-k-core/support/src/test/java/org/apache/camel/k/support/RuntimeSupportTest.java
camel-k-cron/impl/src/test/java/org/apache/camel/k/cron/CronTest.java
itests/camel-k-itests-core/src/test/java/org/apache/camel/k/core/quarkus/deployment/CoreTest.java

- Removed unused imports
- Use hasSize on assertions for array sizes for simplicity and to avoid NPEs
- Use isEmpty on assertions for size checks for simplicity
- Use isZero on assertions for count checks for simplicity
- Avoid chained calls when testing for throws to avoid false positives
Cleanups ... mostly on test code
```release-note
NONE
```

(chores) Test code cleanup

---

support/camel-k-catalog/pom.xml
support/camel-k-maven-plugin/src/it/generate-catalog/pom.xml

Reintroduces the Qute component after Camel Quarkus applied the fix discussed on apache/camel-quarkus#2701 and apache/camel-quarkus#2661.
Retains the ability to exclude components, introduced on commit 4585f3def81ef078bd233399ed8fc371bc050675, in case it is needed in the future.
```release-note
NONE
```

Reintroduces Qute component

---

support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

As part of GH issue apache/camel-k#2541, moved the dependency to the
runtime to ensure it's always present, even with custom base images or other
customizations. This also allow us to manage the dependencies on a
single place instead of spreading them over the codebase.
```release-note
NONE
```

Added quarkus-logging-json as a runtime dependency

---

.github/workflows/ci-build-camel-main.yaml
.github/workflows/ci-build.yml
.github/workflows/pr-validate.yml
itests/camel-k-itests-loader-jsh/src/main/java/org/apache/camel/k/loader/jsh/quarkus/it/JshApplication.java
itests/camel-k-itests-loader-jsh/src/test/java/org/apache/camel/k/loader/jsh/it/JshLoaderTest.java
pom.xml
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateDependencyListMojo.java
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateSupport.java
support/camel-k-runtime-bom/pom.xml

- deps: update to camel-quarkus 2.4.0
- fix: move tests classes to a dedicate package to avoid split package warning
- deps: update directory-maven-plugin to v1.0.0
- deps: update gmavenplus-plugin to v1.13.0
- deps: update maven-pmd-plugin to v3.15.0
- deps: update checkstyle to v8.44
- deps: update directory-maven-plugin to v1.0
- ci: switch to actions/setup-java@v2, use temurin distribution, build on java 17
- deps: force asm version for maven-pmd-plugin
- chore: fix deprecation warnings 
```release-note
NONE
```

camel quarkus 2.4.0

---

camel-k-loader-jsh/impl/pom.xml
itests/camel-k-itests-loader-jsh/src/main/java/org/apache/camel/k/loader/jsh/quarkus/it/JshApplication.java
itests/camel-k-itests-loader-jsh/src/test/java/org/apache/camel/k/loader/jsh/it/JshLoaderTest.java
pom.xml

- deps: update to camel-quarkus 2.4.0
- fix: move tests classes to a dedicate package to avoid split package warning
- chore: remove unused undertow depdendency
```release-note
NONE
```

remove undertow

---

docs/modules/languages/pages/javascript.adoc

There was a very slight grammar issue in the docs regarding JavaScript advanced escape hatches, likely b/c of editing/changing sentence structure over time. 
```release-note
NONE
```

fix(docs): grammar correction in JavaScript docs

---

docs/modules/languages/pages/yaml.adoc

See apache/camel-website#701
This must be merged at the same time as the corresponding camel-k-runtime PR

camel-website-701 RI update attribute name (1.10.x)

---

docs/modules/languages/pages/yaml.adoc

See apache/camel-website#701
This must be merged at the same time as the corresponding camel-k-runtime PR

camel-website-701 RI update attribute name (1.9.x)

---

pom.xml

Camel-dependencies should point to 3.14.1

---

docs/antora.yml

The website build fails with the next error due to some broken links.
```
➤ YN0000: [build:antora  ] [build:antora-perf] [05:59:00.324] WARN (asciidoctor): skipping reference to missing attribute: camel-docs-version
➤ YN0000: [build:antora  ] [build:antora-perf]     file: docs/modules/languages/pages/yaml.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     source: https://github.com/apache/camel-k-runtime.git (refname: release-1.13.x, start path: docs)
➤ YN0000: [build:antora  ] [build:antora-perf] [05:59:00.325] ERROR (asciidoctor): target of xref not found: {camel-docs-version}@components:others:main.adoc#_specifying_custom_beans
➤ YN0000: [build:antora  ] [build:antora-perf]     file: docs/modules/languages/pages/yaml.adoc
➤ YN0000: [build:antora  ] [build:antora-perf]     source: …
```

Fix the Camel-K version for the doc generation

---

camel-k-core/support/src/main/java/org/apache/camel/k/support/SourcesSupport.java

```release-note
NONE
```
Fixes #820

Improve error message during ErrorHander building validation

---

.gitignore
pom.xml
support/camel-k-maven-logging/pom.xml
support/camel-k-maven-logging/src/main/assembly/overlay.xml
support/camel-k-maven-logging/src/main/resources/logback.xml
support/pom.xml

Introduce new module for structured Maven output logging
- Module collects logging artifacts that enable structural Maven output
- Camel K Docker image will use these artifacts to add structural Maven logging to IntegrationKit build output
- Module automatically creates a zip artifact that contains all logging artifacts needed to enable structured logging on a Maven installation
- Zip file is attached to the Maven build and uploaded to the Maven repository
```release-note
feat: Add new module for structural Maven logging
```

Add new module for structural Maven logging

---

support/camel-k-maven-logging/pom.xml

- Jackson v2.13.3
- Logback v1.2.11
- Logstash logback encoder v7.2

chore(deps): Bump dependency versions

---

.github/workflows/depsreview.yaml

(chores) ci: add dependency review check for PRs

---

camel-k-resume-kafka/deployment/pom.xml
camel-k-resume-kafka/deployment/src/main/java/org/apache/camel/k/quarkus/resume/deployment/ResumeFeature.java
camel-k-resume-kafka/impl/pom.xml
camel-k-resume-kafka/impl/src/main/java/org/apache/camel/k/resume/ResumeContextCustomizer.java
camel-k-resume-kafka/impl/src/main/java/org/apache/camel/k/resume/kafka/KafkaResumeFactory.java
camel-k-resume-kafka/pom.xml
camel-k-resume-kafka/runtime/pom.xml
pom.xml
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java
support/camel-k-runtime-bom/pom.xml

This includes a new customizer that handles setting up part of the
resume API in the context.
```release-note
NONE
```

Add preliminary support for the Resume API for Camel K

---

pom.xml
support/camel-k-maven-plugin/pom.xml

- build(deps): bump maven-pmd-plugin from 3.17.0 to 3.18.0
- chore: cleanup camel-k-maven-plugin dependencies
```release-note
NONE
```

bump maven-pmd-plugin 3.18.0 and cleanup camel-k-maven-plugin deps

---

camel-k-core/runtime/pom.xml
camel-k-runtime/runtime/pom.xml

Workaround that mimic what it was done to fix https://github.com/quarkusio/quarkus/issues/27085 - tested locally with Camel K 1.10, it seems the JS routes are running fine.
Ref https://github.com/apache/camel-k/issues/3560#issuecomment-1225740336
```release-note
NONE
```

fix: issue inherited by Quarkus platform

---

docs/modules/languages/pages/yaml.adoc

When the [camel-knative was migrated](https://github.com/apache/camel/pull/6749) from camel-k-runtime to camel, this ProcessorSteps code was not migrated.
```release-note
NONE
```

Doc: Remove unsupported "Extending DSL" section

---

support/camel-k-maven-logging/pom.xml

logback 1.4.1 requires slf4j 2.0.1, which requires additional changes in maven library when used in camel-k to build integrations Read more info from the closed PR https://github.com/apache/camel-k-runtime/pull/902
```release-note
NONE
```

Revert logback uprgade to 1.2.11

---

support/camel-k-maven-logging/pom.xml

logback 1.4.1 requires slf4j 2.0.1, which requires additional changes in maven library when used in camel-k to build integrations Read more info from the closed PR https://github.com/apache/camel-k-runtime/pull/902
```release-note
NONE
```

Revert logback uprgade to 1.2.11 (1.15.x branch)

---

support/camel-k-runtime-bom/pom.xml

The jolokia trait [sets the dependency and version in jolokia.go](https://github.com/apache/camel-k/blob/v1.10.1/pkg/trait/jolokia.go#L66). We should avoid declaring the version there and let camel-k-runtime-bom manage the dependencies.
```release-note
NONE
```

Set jolokia dependency in camel-k-runtime-bom to avoid declaring the dependency in camel-k

---

camel-k-core/support/pom.xml
itests/camel-k-itests-cron/pom.xml
itests/camel-k-itests-webhook/pom.xml
pom.xml

With this PR we provide a bit of dependency cleaning, removing 2 BOMs that are no longer needed and above all, removing the inheritance from `camel-depencencies` that was an headache when bumping camel version (we had to remind to keep aligned in 2 different places).
```release-note
chore: dependency cleaning
```

chore: dependency cleaning

---

pom.xml
scripts/bump.sh

Closes #918
We need to bring back the inheritance to the `camel-dependencies` pom as that contains information for the release. However, I've added an enforcer rule to make sure the `camel-version` is aligned with the `camel-dependencies` version. The first commit of this PR should fail to prove the rule is fine.
```release-note
fix(deps): brought back inheritance to camel deps
```

fix(deps): brought back inheritance to camel deps

---

distribution/src/main/assemblies/repository.xml

With this PR we only include the artifacts related to the actual version. The issue was creating huge distribution artifact containing also previous version of the project (ie, https://repo1.maven.org/maven2/org/apache/camel/k/apache-camel-k-runtime/1.15.0/apache-camel-k-runtime-1.15.0-m2.zip is 1.7 GB!)
Ref https://github.com/apache/camel-k/issues/3826
```release-note
fix(ci): keep version artifact only
```

fix(ci): keep version artifact only

---

support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

https://github.com/apache/camel-k-runtime/pull/927 removed the knative setting as a know http endpoint, we should re-add it.
```release-note
NONE
```

Set knative as a know http endpoint

---

pom.xml
support/camel-k-maven-plugin/pom.xml
support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/support/MavenSupport.java
support/camel-k-maven-plugin/src/main/resources/app.properties

This PR will publish the Quarkus native image builder into the catalog, enabling the possibility to dynamically use it on Camel K (a step towards decoupling).
```release-note
feat(catalog): publish Mandrel image info
```

feat(catalog): publish Mandrel image info

---

support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

Uses camel-quarkus opentelemetry extension for new telemetry capability in catalog
resolves #apache/camel-k#3519
```release-note
feat(catalog): Add telemetry capability
```

feat(catalog) : Add telemetry capability

---

support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

fixes #953 
In Camel-Quarkus 2.16.0 several DSLs have been improved to support the native mode, the metadata needs to be updated consequently.
* Switch the metadata `native` to `true` for the DSLs `groovy`, `kotlin`, and `java-joor` 
* Add the DSL `jsh`
* Set the metadata `sources-required-at-build-time` to `true` when needed to indicate that the sources need to be present while building the native image.
* Set the metadata `native` to `false` for the JavaScript DSL since it is not supported on Mandrel
```release-note
Update DSLs metadata
```

Ref #953: Update DSLs metadata

---

docs/antora.yml

resolves apache/camel-k#4176
The language documentation is missing from the camel-k 1.12.x version documentation
```release-note
Fix website doc camel-k version
```

fix(doc): missing language documentation in camel-k 1.12.x version

---

support/camel-k-catalog-model/src/main/java/org/apache/camel/k/catalog/model/CatalogOtherDefinition.java
support/camel-k-catalog-model/src/main/java/org/apache/camel/k/catalog/model/CatalogSupport.java
support/camel-k-maven-plugin/src/it/generate-catalog-with-exclusions/pom.xml
support/camel-k-maven-plugin/src/it/generate-catalog-with-exclusions/verify.groovy
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

[Backport-1.17.x] fix(#1029): Include miscellaneous components in Camel catalog

---

support/camel-k-maven-logging/pom.xml

This reverts commit c1b49e5bffe9d5c1d0a7e929eacf575474735d1c.
7.4 version dropped support for logback 1.2
https://github.com/logfellow/logstash-logback-encoder/releases/tag/logstash-logback-encoder-7.4
it causes a `NoSuchMethodError: 'java.time.Instant ch.qos.logback.classic.spi.ILoggingEvent.getInstant()'` when using build=routine in camel-k
```release-note
Revert logstash-logback-encoder upgrade from 7.4 to 7.3
```

Revert "build(deps): bump logstash-logback-encoder from 7.3 to 7.4"

---

pom.xml

ubi-quarkus-mandrel is deprecated, in favor of ubi-quarkus-mandrel-builder-image 
https://quay.io/repository/quarkus/ubi-quarkus-mandrel?tab=info
```release-note
NONE
```

Update native image to ubi-quarkus-mandrel-builder-image

---

scripts/sync_cq.sh

fix automatic CEQ update: don't print mvn download statement

---

support/camel-k-maven-logging/pom.xml

`logback-version` is defined in parent camel-dependencies pom and the version is 1.4.8 which is incompatible with slf4j 1.7  packaged in maven 3.8.6 (bundled in Camel K operator), so slf4j-api 2.0 should be defined as dependency, to be retrieved as part of the Camel K operator build.
This is to fix https://github.com/apache/camel-k/issues/4882
```release-note
NONE
````4

Add slf4j-api as dependency, it is required in camel-k to overlay in maven lib

---

examples/cron/pom.xml
examples/groovy/pom.xml
examples/java/pom.xml
examples/js/pom.xml
examples/kafka-source-s3/pom.xml
examples/kamelets-discovery/pom.xml
examples/kamelets/pom.xml
examples/knative/pom.xml
examples/kotlin/pom.xml
examples/xml/pom.xml
examples/yaml/pom.xml
pom.xml

It may happen the io.quarkus version differ to quarkus.platform version so we have to set quarkus-maven-plugin to follow the qurarkus platform version
```release-note
NONE
```

Fix quarkus-maven-plugin to use the quarkus-platform-version property (#86)

---

examples/cron/pom.xml
examples/groovy/pom.xml
examples/java/pom.xml
examples/js/pom.xml
examples/kafka-source-s3/pom.xml
examples/kamelets-discovery/pom.xml
examples/kamelets/pom.xml
examples/knative/pom.xml
examples/kotlin/pom.xml
examples/xml/pom.xml
examples/yaml/pom.xml
pom.xml

It may happen the io.quarkus version differ to quarkus.platform version so we have to set quarkus-maven-plugin to follow the qurarkus platform version
```release-note
NONE
```

Fix quarkus-maven-plugin to use the quarkus-platform-version property (backport 3.2.x) (#86)

---

pom.xml
support/camel-k-maven-plugin/pom.xml
support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy

The camel-quarkus dependencies must come exclusively from quarkus-camel-bom

---

pom.xml
support/camel-k-maven-plugin/pom.xml
support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy

The camel-quarkus dependencies must come exclusively from quarkus-camel-bom (3.2.x)

---

support/camel-k-catalog-model/src/main/java/org/apache/camel/k/catalog/model/Artifact.java
support/camel-k-catalog-model/src/main/java/org/apache/camel/k/catalog/model/CamelCapability.java
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java
support/camel-k-runtime-bom/pom.xml

Update jolokia to 2.0.0
```release-note
feature: add maven artifact classifier to the camel-k-catalog
update: jolokia 2.0.0
```

Fix: add classifier field to the maven artifact abstraction

---

.github/actions/automatic-updates/action.yml
.github/workflows/nightly-automatic-updates.yml

Nightly deploy is activated on the following branches:
* main
* release-3.6.x
* release-3.2.x
```release-note
feat(ci): Add nightly deploy for main and recent release branches
```

feat(ci): Add nightly deploy for main and recent release branches

---

pom.xml
support/camel-k-maven-plugin/pom.xml
support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy

Ref #1156 
Revert to fix camel-k upstream issues with catalog in nightly builds.
Also `camel-quarkus.version` is referenced by camel-k code.
```release-note
NONE
```

Revert camel-quarkus-version removal from PR #1156

---

.github/actions/automatic-updates/action.yml

build(deps): bump actions/setup-java from 3 to 4 in automatic-updates

---

.github/actions/automatic-updates/action.yml

fix(CI): Update setup-java to v4 due to github warnings (3.6 branch)

---

camel-k-runtime/runtime/src/main/java/org/apache/camel/k/quarkus/ApplicationConfigSourceProvider.java

- Since Camel 4.4.0 the noErrorHandler default setting will disable the global Pipe error handler
- Disable the noErrorHandler setting on the camel-kamelet component when the Pipe error handler ref is set
- Relates to Camel K issue https://github.com/apache/camel-k/issues/5242
```release-note
fix: Disable noErrorHandler setting via user properties
```

fix: Disable noErrorHandler setting via user properties

---

pom.xml
support/camel-k-runtime-bom/pom.xml

The sync_cq.sh script is not going to work as it gets the `quarkus.version` from camel-quarkus which is quarkus-core, while camel-k-runtime uses the quarkus.platform which these versions may differ. 
There exists the quarkus-core 3.9.0, but quarkus platform is 3.9.1.
```release-note
Update quarkus platform to 3.9.1
```

Update quarkus platform to 3.9.1

---

support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

the camel-quarkus-opentracing is removed since camel-quarkus 3.0
```release-note
Remove tracing capability
```

Remove tracing capability

---

camel-k-core/runtime/pom.xml
camel-k-runtime/runtime/pom.xml

it seems not required anymore by examing the plugin doc
```release-note
NONE
```

Remove runnerParentFirstArtifacts from quarkus-extension-maven-plugin

---

support/camel-k-maven-plugin/src/it/generate-catalog/verify.groovy
support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/GenerateCatalogMojo.java

Properties modification:
* propEndpoint: "quarkus.opentelemetry.tracer.exporter.otlp.endpoint" => "quarkus.otel.exporter.otlp.traces.endpoint"
* propServiceName: "quarkus.opentelemetry.tracer.resource-attributes" =>  "quarkus.otel.resource.attributes"
* propSampler: "quarkus.opentelemetry.tracer.sampler" =>  "quarkus.otel.traces.sampler"
* propSamplerRatio: "quarkus.opentelemetry.tracer.sampler.ratio" => "quarkus.otel.traces.sampler.ratio"
* propSamplerParentBased: "quarkus.opentelemetry.tracer.sampler.parent-based" => "quarkus.otel.traces.sampler.parent-based"
```release-note
fix(trait): Telemetry trait properties change
```

fix(trait): Telemetry trait properties change
